### ISSUE TITLE
Update puredata.info 

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#1]
Regarding Pd's documentation, we need to revise and update puredata.info, which is usually what comes first on google searches for pd resources, see 

<img width="700" alt="Screen Shot 2021-05-30 at 03 51 04" src="https://user-images.githubusercontent.com/5360142/120108622-61539c00-c13c-11eb-9375-e9242578ad3b.png">

This issue is to pin point some things we need to do.

**Comment by porres** [comment]
> @umlaeute , how can you grant me admin powers to https://github.com/pure-data/pddp

can i @umlaeute ? :)

**Comment by umlaeute** [comment]
> can i @umlaeute ? :)

what?

iirc i've granted you admin rights early in june. (and i just checked and you *are* admin)

**Comment by porres** [comment]
yeah, I realize that now, hahah, sorrry

**Comment by porres** [comment]
We need to work on the contents table and better organize 'tutorials', 'manuals' and 'books about Pd', it's not well organized, specially, 'books about Pd' is kinda hidden.

**Comment by umlaeute** [comment]
here's an overview of forks, sorted alphabetically https://puredata.info/downloads/by-category/distribution
