### ISSUE TITLE
[pre wip] pandoc and html reference

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pddp#10]
This is a proposal to handle html reference (and more?) via `.md` files transformed with [pandoc](https://pandoc.org/).

There is a `template.txt` that is used when pandoc converts the `.md` to `.html` files that injects header and footer which includes custom `.css` and `.js` to allow the user to change the font (serif - sans-serif) and the screen mode (dark mode - light mode) as in #9.

The custom css can handle all the normal tags that are allowed in the standard [markdown](https://www.markdownguide.org/cheat-sheet/) that pandoc converts.

I'm not sure if we need this but if we need to handle the **html reference docs** in `.md` this will do. (i had down-voted this years ago https://github.com/pure-data/pure-data/pull/171 in the context of the manual, mostly because the manual was already html in the first place.)

files are in https://github.com/Lucarda/Lucarda.github.io/tree/main/pandoc-and-reference

it can be previewed on https://lucarda.github.io/pandoc-and-reference/ the first 4 or 5 objects.

**Comment by porres** [comment]
what's up with this?

**Comment by Lucarda** [comment]
I think we don't need this.

Did you see the preview?

**Comment by porres** [comment]
> I think we don't need this.

I dunno, might be good to have, but maybe not worth it... it actually feels better to me if we have reference as subpatches in the help files, see https://github.com/pure-data/pddp/issues/6 - after we do that (and I'm working on it), we can think about an html expansion...

do you feel like closing this for now?

**Comment by Lucarda** [comment]
> it actually feels better to me if we have reference as subpatches

Totally.

Closing this.

**Comment by porres** [comment]
I can see the benefit of an online html reference, I'll keep this opened

**Comment by porres** [comment]
or maybe create a new one :)

**Comment by porres** [comment]
new: https://github.com/pure-data/pddp/issues/46
