### ISSUE TITLE
gatom: no method for 'x' is misleading

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#101]
some people get thrown of by the errors produced by the gui boxes (number/symbol/list) because of its rather obscure real name (gatom). Someone on facebook was saying "I don't see a "gatom" object"...

Not sure how to improve this or what is possible, could we maybe use at least the other internal names such as 'floatatom' / 'symbolatom' / 'listbox'? This would also be more specific for each case.

**Comment by umlaeute** [comment]
just instruct people that they can find the source of an error by Ctrl-clicking the error message?
https://deken.puredata.info/tip-of-the-day/tips/tip-20/

**Comment by porres** [comment]
"Not sure how to improve this or what is possible, could we maybe use at least the other internal names such as 'floatatom' / 'symbolatom' / 'listbox'? This would also be more specific for each case."

renaming all to 'gui box' instead of 'gatom' would be an improvement and this is now their 'official new name'.

Instructing how you can find the source of an error by Ctrl-clicking would also be good and I have to think where to put this...

**Comment by porres** [comment]
> Instructing how you can find the source of an error by Ctrl-clicking would also be good and I have to think where to put this...

surely in the manual, but also, this is already into "tip of the day" I assume, right? If not, @abreubacelar can add it

**Comment by umlaeute** [comment]
- Anybody can create a tip of the day (including you)
- how about this: https://pd.iem.sh/tipoftheday-plugin/tips/find-the-origin-of-an-error-message/

**Comment by porres** [comment]
closing in favor of https://github.com/pure-data/pddp/issues/149
