### ISSUE TITLE
[Wip] Pd Manual via HUGO and .md files.

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pddp#105]
I had worked on: 

https://github.com/Lucarda/pdmanual-hugo

it has all the manual html files converted to `.md` and it builds with HUGO.

I had taken away all numbering in the headings so the content can be easily move up or down without breaking the internal links.

pros:
- easier to edit  
- cleaner `doc/1.manual` final folder

cons:
- added dependency on HUGO
- not resolved yet how the build process should be but it will be harder than what we got now.

ping @umlaeute @porres @millerpuckette

**Comment by Lucarda** [comment]
this repo: https://git.nubegris.com.ar/lucarda/pure-data-hugo

builds the html manual from `.md` files using HUGO via `makefile.gnu` or `autotools`

it has been tested on Windows and Linux.

To build install hugo in your system:

- Windows/MinGW
	`pacman -S mingw64/mingw-w64-x86_64-hugo`

- Linux(Debian)
	`sudo apt install hugo`

- macOS
	`brew install hugo`
	
also ping @danomatika @Spacechild1

**Comment by porres** [comment]
should we close this? I don't see this as an 'issue', and there's already a draft PR at https://github.com/pure-data/pure-data/pull/1822 can we discuss this over there?
