### ISSUE TITLE
different extensions for html references

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#107]
slop~'s html reference is 'htm' while others are 'html', why not make them the same extension?

**Comment by porres** [comment]
seems the standard for pd is 'htm' but we introduced 'html' in expr and fudi

**Comment by Lucarda** [comment]
this is a really minor implementation detail. `.htm` has been inherited from a long time ago.

You can rename `expr` and `fudi`.


PS: https://github.com/pure-data/pure-data/pull/1822 include all files as `.html` and do harder *renames*.
