### ISSUE TITLE
'text editor' mentioned in the manual doesn't exist

### ISSUE THREAD

**Issue by abreubacelar** [pure-data/pddp#113]
on http://msp.ucsd.edu/Pd_documentation/x2.htm#s2.5 section "changing the text" we read:

>If there's more than a small amount of text (in a comment, for example) you might want to select the text and choose "text editor" from >the Edit menu, which opens a text editing window with a copy of the text in it. Hitting "send" in that window is exactly equivalent to >retyping the text into Pd; you can send it to more than one box in sequence if you want. 

but i don't find this text editor... is this something old that doesn't exist any more or am i missing something?

**Comment by porres** [comment]
> is this something old that doesn't exist any more

Surely, thus it must be removed from the manual.

I don't remember seeing this before so it must be really old. Perhaps @umlaeute can tell us about it :)

**Comment by umlaeute** [comment]
the text editor was dropped with 0.43 (the menu item was removed in https://github.com/pure-data/pure-data/commit/dc79a38f5664055a5a8b9eb508917931fdefccd4, but it had been non-functional since https://github.com/pure-data/pure-data/commit/216f7326b64cbacca5967cb7be4175aa9c770e50)
