### ISSUE TITLE
x2.htm says MAX doesn't have video library

### ISSUE THREAD

**Issue by abreubacelar** [pure-data/pddp#123]
2.1 overview we read:

> Pd is a real-time graphical programming environment for audio and graphical processing. It resembles the Max/MSP system but is  much simpler and more portable; also Pd has two features not (yet) showing up in Max/MSP: first, via Mark Dank's GEM package, Pd can be used for simultaneous computer animation and computer audio. Second, an experimental facility is provided for defining and accessing data structures. 

but max has jitter, right? https://docs.cycling74.com/max7/vignettes/working_with_video_in_jitter_topic

**Comment by porres** [comment]
yeah, that's a bit outdated :)
