### ISSUE TITLE
[netreceive] only sends message in TCP and help file unification

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#126]
In the documentatin it says that In UDP you have to send at least one message forward through the connection for backwards messages to find their way back to the 2nd outlet in [netsend], but when trying to do so I get the error "netreceive: 'send' only works for TCP"

This seems intentional so the documentation is wrong.

Also, we could unify the help files of netsend/netreceive like alll other pair of objects are already uniffied (send/receive - tabsend~/tabreceive - oscparse/oscformat - etc).

**Comment by porres** [comment]
documentation also says that you can use an additional port argument for the connect message in [netsend] to specify a port number for messages sent back from receiver. I couldn't get this to work really and I am pinging @umlaeute / @spacechild and @danomatika for help confirming how this works.

**Comment by porres** [comment]
> I couldn't get this to work really

I made changes to the documentation already which closes this. I am still keeping this information but in the reference only but will revise or include an example when I can confirm that this works and how.

**Comment by danomatika** [comment]
Yes, it's correct that `[netreceive]` can only reply if it's using TCP as TCP is bidrectional. For bidrectional UDP, you'd need an additional sender built-in....

...however `[netsend]` can do this for UDP as it *can* have a built-in receiver. The equivalent `[netsend]` to talk to with the existing example would be something like:

<img width="540" alt="Screen Shot 2023-01-03 at 9 37 33 AM" src="https://user-images.githubusercontent.com/480637/210323552-43f76fa9-4350-4796-b9ed-377a4952bfda.png">

This is why the simple example lists it under UDP only and not under TCP, but you are right in that it could be better explained with a subpatch and a pair of `[netsend -u]` which talk to each other.

Conceptually the model doesn't match the send/receive pair for UDP but it does work. I think, as PD grew, the receiving option was grafted into `[netsend]` at some point.

It might be good to double check if this is actually a bug and if `[netreceive -u]` should allow for handling two ports as well...

**Comment by porres** [comment]
Ok, made it work, I can confirm this happens, a [netsend] can send to another [netsend]. The [netsend] to the left gets values from [netsend] to the right and sends value to a [netreceive] that's listening to the first specified port (and which cannot send back to [netsend], neither it can listen to the second specified port).

![Screen Shot 2023-01-04 at 12 12 57](https://user-images.githubusercontent.com/5360142/210586563-da284df4-4720-4044-b845-245fd0b9bff3.png)

**Comment by umlaeute** [comment]
> What about setting two ports for TCP? I can't make anything happen.

why would you want to do that?``

**Comment by porres** [comment]
> why would you want to do that?

To be honest, I don't know why would someone do that with UDP and it wasn't clear wether this would work only for UDP. All I really want is to understand this and document it :)

**Comment by porres** [comment]
Ok, I see then that this 2nd port number is only meaningful for UDP and this setup with 2 [netsend] objects. We really need a subpatch to show this in action.

One way or another, help file was just wrong to say "In UDP you have to send at least one message forward through the connection for backwards messages to find their way back." This is not really true, I don't have to send anything and [netsend] does get info from the other [netsend].

Also, other information was ambiguous and not clear. I will try to work on something and post here to see if it makes sense.

Thanks

 that In UDP you have to send at least one message forward through the connection for backwards messages to find their way back to the 2nd outlet in [netsend], but when trying to do so I get the error "netreceive: 'send' only works for TCP"
