### ISSUE TITLE
rename 'Pd Documentation' file to 'Pd Manual' as well.

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#13]
Under the 'Help' menu, Pd Help directs to 'Pd Documentation', which is like a manual.

One idea is to change 'help' to 'documentation'

**Comment by danomatika** [comment]
I feel “Documentation” is a bit formal/general. I would suggest “Pd Manual”

**Comment by porres** [comment]
I also feel it should be "Manual", but then the file refers to itself as 'Documentation', and I wonder if we can also rename it to 'Maunal'. I actually already opened a discussion about this somewhere else.

**Comment by porres** [comment]
So, https://github.com/porres/pure-data/commit/84f665af5653ce8830ee196eec98e28cace2a0ef renames 'Pd Documentation' to 'Pd Manual'.

Now, I can't find where in the code I can change the menu entry to 'Pd Manual' instead of 'Pd help', can you help me @danomatika ? Weirdly enough, I found an entry that instead is actually 'manual' and not help at https://github.com/pure-data/pure-data/blob/master/tcl/pd_menus.tcl#L359

**Comment by umlaeute** [comment]
> Now, I can't find where in the code I can change the menu entry to 'Pd Manual' instead of 'Pd help'

there is no such code in Pd. (it also doesn't show anything like "Pd help" on my system).

afaict, this is a pure macOS thing (either mandated by some apple guideline and/or brought to you by Tcl/Tk-on-macOS) that gives you an automatic "<Application> help" entry in the Help-menu.

**Comment by porres** [comment]
> (it also doesn't show anything like "Pd help" on my system).

what does it show?

my screenshot 

<img width="289" alt="Screen Shot 2021-11-19 at 19 14 26" src="https://user-images.githubusercontent.com/5360142/142698313-6975bbb5-74e9-4cb7-8bdd-f13af15fb8f3.png">

**Comment by danomatika** [comment]
Yes, I forgot that the “Pd Help” entry is the standard entry provided by the system. You can only disable it, not rename.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by porres** [comment]
Ok, but how is this shown in other systems, as 'Pd Manual'? 

If I'm not mistaken, maybe that's how I remember it used to be and changed somehow on macOS?

**Comment by porres** [comment]
What if we standardize this and have 'help' open a new introduction section, something like 'welcome to Pd'?  This would give an overview of the documentation and Pd in a couple of paragraphs.

We can then have an actual 'manual' entry, pretty clear where people can't miss!

**Comment by danomatika** [comment]
Yes, I had a similar thought. In my opinion, we want the menu item to be consistent across the platforms. If we only have one menu item to open the HTML doc and it *must* be "Pd Help" on macOS, then it follows to keep that naming for the other platforms. However, as you suggest, we could use "Help" for something more of an overview such as links to important topics and resources while a second "Manual" menu item which opens the more detailed HTML doc. I don't think it should be two menu items which open different chapters in the HTML, but Help should open a separate page altogether.

**Comment by porres** [comment]
> I don't think it should be two menu items which open different chapters in the HTML, but Help should open a separate page altogether.

YUP!!!

**Comment by Lucarda** [comment]
May be [this editable .md](https://nc.nubegris.com.ar/index.php/s/5z4GMqa5HKdj3Lm) helps prototyping the contents of the html?

**Comment by umlaeute** [comment]
> In my opinion, we want the menu item to be consistent across the platforms.

i have no special objection, however i think in *general* there is no reason to force platform-specific behaviour onto other platforms.
e.g. every macOS application has a menu `<Application>` (e.g. `Pd`). it would be weird to have this menu on other platforms.

the specific case of a "Pd Help" entry  is of course more agreeable (as it is a sensible entry anyhow (otoh, it is also a bit tautological: why do i need an entry "Pd Help" in the "Help" menu of "Pd"?))

**Comment by danomatika** [comment]
>e.g. every macOS application has a menu <Application> (e.g. Pd). it would be weird to have this menu on other platforms.

I'm not suggesting to add overly platform specific things to other platforms. In this case, it's clearly something that exists across all, so it's easier to use the general naming.

**Comment by porres** [comment]
I'll make this issue just for renaming  'Pd Documentation' to 'Pd Manual'. 

we can discuss about the other thing in my new issue. https://github.com/pure-data/pddp/issues/15
