### ISSUE TITLE
typos in doc/5.reference/

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pddp#138]
append-help.pd:87: beggining ==> beginning
array-object-help.pd:682: examle ==> example
inlet-outlet-help.pd:64: preffered ==> preferred
list-help.pd:218: lenght ==> length
moses-help.pd:44: Th ==> The
netsend-receive-help.pd:102: Addres ==> Address
netsend-receive-help.pd:185: Addres ==> Address
netsend-receive-help.pd:218: Addres ==> Address
netsend-receive-help.pd:247: witn ==> with
pack-help.pd:40: examle ==> example
pd-messages.pd:50: direcctly ==> directly
pointer-help.pd:167: rigt ==> right
print-help.pd:24: supresses ==> suppresses
route-help.pd:95: examle ==> example
send-receive-tilde-help.pd:98: proprty ==> property
sliders-help.pd:588: widht ==> width
text-object-help.pd:311: messge ==> message
text-object-help.pd:869: examle ==> example
trigger-help.pd:72: examle ==> example
unpack-help.pd:37: examle ==> example

**Comment by porres** [comment]
I was looking for that tool to check typos, what do you use again?

**Comment by umlaeute** [comment]
`codespell`.

What triggered my search this time was the `Th` in the moses-help.pd (which I just stumbled upon, and which was not detected by `codespell...`)

mind you, that i just pushed a fix to your `Documentation` branch.

**Comment by porres** [comment]
well, I pushed it to the wrong branch though :(
