### ISSUE TITLE
Improve 'testone' and use [vu] GUIs

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#139]
It's be much better to include [vu] meters to show us input levels (peak and rms) instead of atom boxes.

In doing so I reorganized the patch a bit and here's a preview I'm working on right now.

![Screen Shot 2023-03-19 at 14 18 03](https://user-images.githubusercontent.com/5360142/226194925-c5dda1eb-2871-431d-b2bd-85f79b81c72c.png)

i also made some other fixes, like the subpatch generating random midi note outs wasn't really send random notes.

**Comment by umlaeute** [comment]
I think the "input hipass" shouldn't be outside the section.

Also shouldn't/couldn't the input and output sections be more separated (right now, the output-toggle seems to be related to the input vu-meter)

**Comment by Ant1r** [comment]
Also, while I like the vu-meters, I think that the number boxes are useful in some cases, maybe we could have both?

**Comment by porres** [comment]
current draft

![Screen Shot 2023-03-19 at 16 19 32](https://user-images.githubusercontent.com/5360142/226203832-adfeb008-0759-4e97-ad16-99de3d66e736.png)

> number boxes are useful in some cases, maybe we could have both?

let me see

**Comment by porres** [comment]
> let me see

current mock up, work in progress...

![Screen Shot 2023-03-19 at 16 40 36](https://user-images.githubusercontent.com/5360142/226204893-9d797c3f-ad2a-4708-aa90-2590b8122583.png)

**Comment by porres** [comment]
done!

![Screen Shot 2023-03-19 at 17 22 58](https://user-images.githubusercontent.com/5360142/226206846-c6c5a8b7-b73e-45a7-ae63-8d84a170c5b4.png)

**Comment by porres** [comment]
More considerations: 
- add a single vu for the tone generator.
- the channel assignment can jump wider and reach maybe 64 or even 128 channels. I don't see the point of small jumps of just 2 channels
- the testtone16 that's also sitting in the same folder is not that useful. It has the the very old layout and I don't want to edit it too... most people aren't aware of it because it doesn't get called. The current example not only can test 16 channels, but also 32 and could be expanded to even more as in my remark above. I say we just delete it.

**Comment by porres** [comment]
> the channel assignment can jump wider and reach maybe 64 or even 128 channels. I don't see the point of small jumps of just 2 channels

I now see that it moves in 2 channels and then it jumps 6 and 8 channels at the very end...

makes more sense to me to jump in groups of 8 and this allows us to go up to 64 channels, which is a good magic number.
