### ISSUE TITLE
Add sections to Manual

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#14]
- messages you can send to and receive from Pd (I already have a commit that documents messages to Pd in the help files - see https://github.com/pure-data/pure-data/pull/1455/commits/640cce0fa3d0f5b2e62769ffa3b6a20ed77e7156 - but we can also add it to the manual). Here's another parallel discussion => https://github.com/pure-data/pddp/issues/20 (this also mentions "#midi" messages.
- Dynamic Patching (with also examples [as in a 'tutorial'] maybe)
- Escaping characters
- 'control' concept and 'control' vs 'audio' rate
- path syntax and accessing files "./" "../" etc.

**Comment by porres** [comment]
Specially, it'd be good to have a chapter going through ALL AND EVERY MENU ENTRY, showing screenshots and showing what they all do!

With many things to be added to the manual, a major overhaul with new chapter numbers and stuff may be needed, what do you think @Lucarda?

**Comment by porres** [comment]
We can also get many ideas and stuff from FLOSS Manuals...

**Comment by Lucarda** [comment]
> Specially, it'd be good to have a chapter going through ALL AND EVERY MENU ENTRY, showing screenshots and showing what they all do!

I think screen-shots are not necessary for this. I prefer giving this info as text only. There are menus that are going to change soon and updating screenshots wastes space in git HEAD.(i.e cloning the repo is bigger in size with the unnecessary binary of each old version of the image file). We don't really need a pic of the unfolded menu "put" or the others menus.

> With many things to be added to the manual, a major overhaul with new chapter numbers and stuff may be needed, what do you think @Lucarda?

&#128077;

**Comment by Lucarda** [comment]
May be if we have the "github pages" we can add sections there.

**Comment by porres** [comment]
Extra (for another issue/PR)
Document 'window menu'
Document 'edit preferences'
I think it'd be nice if we had a caption for all pictures in the manual
