### ISSUE TITLE
I don't like some of the examples for iemguis

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#143]
I am abusing a rather obscure feature of tcl/tk, which activates the GUI in the background. Modern gui frontend don't work this way and this means this is not reproducible or possible in PurrData / Pd-l2ork and PlugData. 

Maybe it's just best not to rely or promote this behaviour... specially that with the new gui rewrite, creating forks and using new frontends could be a more common reality...

This is abused inthe 'discrete' examples for sliders and nbx, which is also just a bad hack for something that could be a built in added functionality if people really want it.

Hence I think I will just remove them... I may try to think of some other example instead...

I also have a rather weird example for canvas ([cnv]) where I also present a similar hack to make it behave like something it is not and I do it by hiding a number box behind it. [cnv] is not clickable but, again, feels like promoting hacky and non conventional behaviour and something that probably should not be in the canonical documentation...

**Comment by umlaeute** [comment]
> I am abusing a rather obscure feature of tcl/tk, which activates the GUI in the background. 

no.
this is a (probably obscure) "feature" of Pd itself, which handles the focus.

if Pd-l2ork/Purr Data/PlugData implement this differently, then they are disgressing from Pd-vanilla. (which could be considered a bug on their side)

**Comment by porres** [comment]
maybe let's not debate the degree os obscureness of the feature, but I agree it is a "feature", or it is what it is... but doesn't this come from simply the way tcl/tk works?

I also think it's a bug/digression from other forks, but I believe there's nothing one can do about it as these other gui front ends behave differently.

One way or another, I didn't like the examples and I didn't think it was worth promoting them, it felt more like hacks, like 'how to turn your sider into a discrete slider', and frankly, if users would like to have a discrete slider, it makes more sense to me that we implement this as a built in feature of the object

**Comment by umlaeute** [comment]
> but doesn't this come from simply the way tcl/tk works?

i don't see how.
it does come from the fact, that Pd(-core) is handling the focus, rather than the GUI toolkit.

**Comment by porres** [comment]
I made changes that were merged, so closing this
