### ISSUE TITLE
document temppath for when you run pd with cmd line

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#144]

**Comment by umlaeute** [comment]
what for? where?

how is the use of a variable named `temppath` user-facing?

**Comment by umlaeute** [comment]
the fact that you can specify additional search-paths via the cmdline, is already documented at http://msp.ucsd.edu/Pd_documentation/x3.htm#s4

(and the variable name `temppath` is not user-facing and should therefore not appear in any *user*-targeting documentation; but you are probably not talking about the variable name)
