### ISSUE TITLE
document multichannel in fft~ objects

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#153]
hmm, not iimlemented yet though, just rfft~ seems to take it so far

**Comment by Spacechild1** [comment]
rifft~ is multichannel, it just missed the `CLASS_MULTICHANNEL` flag. Fixed on latest develop ([424ad0b](https://github.com/pure-data/pure-data/pull/2003/commits/424ad0b58a7362c5aae06cb984af1f1bc9a3792c))
