### ISSUE TITLE
rename chapter files

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#16]
currently we have 'x1' / 'x2' / 'x'3 ... x '6'...

why not have the name of the chapters? 

this could be 1-intro / 2-operation / 3-install-config / 4-externals / 5-status / 6-install-from-source

**Comment by Lucarda** [comment]
IIRC _renaming_ a file wipes all its git history (at least from the github web interface).

_Rename_ can be done (and includes lots of surgery in the inter links) but there's no benefit. I prefer to keep it "as is". But that's my opinion.

**Comment by porres** [comment]
> renaming a file wipes all its git history

doubt it, but even so, so what? It's not a code.

> there's no benefit.

how so? The benefit is being able to know what the chapter is about. I either have to memorize (which even I haven't yet) or always open them all to see what they are. It's bad, and there's no benefit or reason to have encripted file names

**Comment by Lucarda** [comment]
The normal thing is to open `index.html`. OTOH this can be done but (i think) we should wait https://github.com/pure-data/pure-data/pull/1460 and https://github.com/pure-data/pure-data/pull/1455 get merged.

Is this ok with you?

**Comment by Lucarda** [comment]
> doubt it, but even so, so what?

So what?: I dont care.  "doubt it" I don't. I have seen it happen on one of eric lyons` repos.

**Comment by porres** [comment]
> I dont care.

hmm, cool then, so I, I don't either :) 

> The normal thing is to open index.html. 

that is true.

> we should wait pure-data/pure-data#1460 and pure-data/pure-data#1455 get merged.

yeah, this is not for now

**Comment by Lucarda** [comment]
We should first ask @millerpuckette for a green light on renaming files and folders of the manual.

**Comment by porres** [comment]
I really wanna do this, I never go for index and a clear description of the chapter contents would be good... this is on my list for the next update

**Comment by Lucarda** [comment]
Wait. and lets talk this.

`index.html` is a special name. Is like a canonical default for servers and browsers. 

So please don't include renames in your `documentation` branch until we are really sure what to do.

Also note https://github.com/pure-data/pddp/issues/105 that has clearer dir and filenames. It also lets you edit the manual via the `.md` files. Please try to get HUGO and test how it works. see https://git.nubegris.com.ar/lucarda/pure-data-hugo readme.


PS: the explanation is not very good as I'm on something else right now.

PS2: Don't rename the files.

**Comment by porres** [comment]
chill, it's on my to do list for the next release but not on my plate right now :)

**Comment by Lucarda** [comment]
Ok. just remember that changing the filename will also need to change all internal links. `index.html` is needed by @millerpuckette  on the server side of http://msp.ucsd.edu/Pd_documentation/

**Comment by porres** [comment]
I can start a "manual branch" and I can use it to do more changes and improvements to the text, and then I could merge it to my documentation branch

**Comment by porres** [comment]
there are lots of things to improve and add to the manual that I would like to

**Comment by Lucarda** [comment]
> I can start a "manual branch" and I can use it to do more changes and improvements to the text, and then I could merge it to my documentation branch

sure.

**Comment by porres** [comment]
after renaming and reorganizing pictures, I'd really like to deal with this as well
