### ISSUE TITLE
[delay] help, add note about a delay of zero/no argument

### ISSUE THREAD

**Issue by ulioidle** [pure-data/pddp#160]
[del] with no arguments or 0 is not no delay, it is a delay of 1 event in the scheduler. This seems like it should be mentioned in the helpfile, it can bite you if you are unaware of it and it comes in handy on occasion.  
![del](https://github.com/pure-data/pddp/assets/8304564/c9d57f40-0e64-4ff5-bf4c-b5cbc6785ba7)

Edit: [pipe] also has this behavior.

**Comment by porres** [comment]
Technically it is  "0 delay" but it is not a bypass and it surely skips the order of execution. Not sure how to deal with this yet...

**Comment by porres** [comment]
and plese don't use floats directly into object boxes, a baby panda dies when you do that

**Comment by ulioidle** [comment]
> Technically it is "0 delay" but it is not a bypass and it surely skips the order of execution. Not sure how to deal with this yet...

I think most users are more interested in the practical, it makes the event happen later than it should even if that later is not in real time. The technical explanation seems more suited to the scheduler section of the manual and not the help files which are more about practical application and reference. I think acknowledging it and maybe an explanation regarding why/when it is ok to use to break order of execution would be enough. 
![ddd](https://github.com/pure-data/pddp/assets/8304564/3c353cd6-b2ae-49d8-8a6d-2bbf6b859e9f)
I do things like this on occasion and I suspect it can cause problems at times, but it can also produce a much cleaner and easier to read patch, but I am hesitant to share such uses with other people since I may just be opening a can of worms for them down the line. Then again I have been doing this sort of thing for about a year now and have never had a problem so my fears maybe unfounded? And in one patch a [del 0] before a [closebang] was the difference between a dangerous pd crashing abstraction and a very useful and safe abstraction. The latter example is probably beyond the scope of the help patch but the former seems in its scope and knowing if such things are sane or even just knowing that they can be done but only advised as a last resort would be very helpful. 

> and plese don't use floats directly into object boxes, a baby panda dies when you do that

Sometimes it is perfectly reasonable and safe to do so, such as my contrived example.

**Comment by porres** [comment]
> but I am hesitant to share such uses with other people since I may just be opening a can of worms for them down the line

more baby pandas will surely die

**Comment by porres** [comment]
I don't think use cases of [del 0] ought to be promoted and we probably need to see what the hell was crashing your patch with [closebang] as it seems this is more of a hack to bypass a bug than an use case.

A delay in the middle of a [trigger] chain is also weird as it should just be in the end of it... so I don't know yet what to do but I'm certain not to put such weird examples out there as I fail to see the use case. So maybe just some technical remark somewhere

**Comment by ulioidle** [comment]
> I don't think use cases of [del 0] ought to be promoted and we probably need to see what the hell was crashing your patch with [closebang] as it seems this is more of a hack to bypass a bug than an use case. It was before [canvasdelete], not a [closebang], memory failure. Image in that thread is out of date and shows the version which would crash pd on undo. 
 
It is a dynamic patching/autopatching collision, a [del 0] before the [closebang] made the autopatching happen before the close.
https://forum.pdpatchrepo.info/topic/14071/msg-a-message-object-bug-fix

I agree that the use cases for [del 0]/[pipe 0] are almost certainly niche and best not promoted, but we need something and maybe show how it can cause problems.

**Comment by porres** [comment]
> https://forum.pdpatchrepo.info/topic/14071/msg-a-message-object-bug-fix

that's a pretty intense hack :)

**Comment by ulioidle** [comment]
> > https://forum.pdpatchrepo.info/topic/14071/msg-a-message-object-bug-fix
> 
> that's a pretty intense hack :)

How about an entire macro system as an abstraction :) The abstraction in an older form is about 7 posts down if you want to dig in. It is fairly useful and a real time saver but have never found a way to make it work well for general use/release. It is a fairly complete macro system other than not playing well with redo. 
https://forum.pdpatchrepo.info/topic/14071/msg-a-message-object-bug-fix

**Comment by porres** [comment]
still not sure what to do with this... I'm open to suggestions @umlaeute and @spacechild1

**Comment by porres** [comment]
no suggestions, no ideas, marking as won't fix

**Comment by porres** [comment]
Ok, now I'm revising the manual and chapter 2 mentions about [delay 0] and stuff, so I made remark on it and told people to check the manual
