### ISSUE TITLE
throw~/catch~ docs remaining issues

### ISSUE THREAD

**Issue by dromer** [pure-data/pddp#167]
language/description in https://github.com/pure-data/pddp/blob/main/md-reference/throw~.md and https://github.com/pure-data/pddp/blob/main/md-reference/catch~.md are correct.

However the help.pd is still wrong: https://github.com/porres/pure-data/blob/Documentation/doc/5.reference/throw~-catch~-help.pd#L97

`A [throw~] object copies its input to a local buffer which all [catch~] objects of the same name read from.` 
Is incorrect, there is only `one [catch~] object of the same name` allowed.

Also md-reference files are missing the line `They may be in different windows or even different patches.` - is this still relevant info, or always assumed for send/receive type operation?

**Comment by porres** [comment]
disconsider MD files, they're not officially part of Pd or anything yet, they are still to be written, revised and officially included
