### ISSUE TITLE
put manual figures in a subfolder and reorganize them

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#17]
- can't we put them in a subfolder for keeping things better organized?
- also, some are in a different format

**Comment by Lucarda** [comment]
roughly the same as https://github.com/pure-data/pddp/issues/16#issuecomment-974794861

It can be done but there's no much need (at least to me) to "better organize" the `/doc/1.manual` folder.

I think `doc/8.topics` should indeed be prepared for a "better organization" as there might be more to come in this folder.

**Comment by porres** [comment]
> there's no benefit.

why do you think there is no reason to make things better organized? Think about someone going through the files and they just see a bunch of pictures and they can't even see thee actual manual files. I mean, I get you may not feel this is important, but is there an actual reason to oppose? At all?

I can do the work myself...

**Comment by Lucarda** [comment]
we should wait https://github.com/pure-data/pure-data/pull/1460 and https://github.com/pure-data/pure-data/pull/1455 get merged.

Is this ok with you?

**Comment by Lucarda** [comment]
we should wait https://github.com/pure-data/pure-data/pull/1460 and https://github.com/pure-data/pure-data/pull/1455 get merged.

Is this ok with you?

**Comment by porres** [comment]
> Is this ok with you?

of course

**Comment by porres** [comment]
Hey, how about we do this next? Also... now we have two naming conventions for pictures... should be just one...

I like the idea of not having descriptive names, just order them under the section, like 1.2.1.A 1.2.1.B or someting

**Comment by Lucarda** [comment]
> 1.2.1.A 1.2.1.B or someting

this is good for a frozen doc but if you change the order of a subsection or add a new subsection then many filenames are out of sync. now that we can i think is better to support descriptive filenames.

if you are ok i could move all files to a `img` folder.

**Comment by ben-wes** [comment]
I could rename all existing images in a way that names are consistent. should i? Will also read through all docs later today once more...
