### ISSUE TITLE
[soundfiler] not saving files and default values for flags

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#177]
The example uses a '/tmp/' directory to write to, but this directory doesn't exist, so noting gets saved.

I think it would best to also use [openpanel] and [savepanel] in the examples by the way.

Also, the documentation doesn't specify what are the default values for all flags.

**Comment by porres** [comment]
I also noticed that normalization seems to be the default option for 'write', so no need to use the -normalize flag!

**Comment by porres** [comment]
> I also noticed that normalization seems to be the default option for 'write', so no need to use the -normalize flag!

This is only true if the arrays have values greater than -1 to 1

**Comment by porres** [comment]
I finished a rewrite of the whole help file, I just need confirmation if the default endianess is 'l' (little), help @umlaeute and @spacechild1

**Comment by umlaeute** [comment]
> The example uses a '/tmp/' directory to write to, but this directory doesn't exist, so noting gets saved.

so what is the problem?
the help-file is to document an object, not to create artifacts.
esp. it shouldn't create artifacts in the `docs/` folder.

i understand your desire to not create any error-message regardless which msgbox you click, but i think that writing random files to a directory that (iff writable) persists, is worse than not writing at all.
