### ISSUE TITLE
add a bit more color in the background of arrays

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#179]
The themes of the help files are quite modest and we just got some GUIs that are a bit grayed, this remotes to this other 'issue' -> https://github.com/pure-data/pddp/issues/63\\

What annoys me now is that arrays are out of this 'theme' and the sheer whiteness backgroundlessness they have kind of distorts with the theme. My idea is to have a lighter gray [cnv] in their background. I know people may wonder why the array seems colored, as if it was some property, but they can also just learn this trick of using a canvas, and I see other people use the same trick and we can give this idea to people.

For the [output~] abstraction I did something similar. I have a lighter gray canvas behind the number box and comments, because being plain white looked bad to me.

see

![Screen Shot 2023-11-30 at 00 58 03](https://github.com/pure-data/pddp/assets/5360142/861a735d-2f06-4525-81ca-3b3a188a8fdc)

here's a test with the recent changes I did to the [soundfiler] help file.

![Screen Shot 2023-11-30 at 01 00 20](https://github.com/pure-data/pddp/assets/5360142/339a27d2-f8af-4bde-93af-54a5e4322845)
![Screen Shot 2023-11-30 at 01 00 29](https://github.com/pure-data/pddp/assets/5360142/302bb381-b179-402a-946f-b41359ac6049)

**Comment by umlaeute** [comment]
i would be super-careful with over-theming the documentation.

i really think that that guy on the pd-list who criticized the grey toggles had a point: if you create a table then it will not be grey.
with toggles, you can at least change the background color, but with tables you are *mimicking* a background color and leave people wondering how you did that.
(and i don't feel this is a great way to "make people learn a trick"; if things get too confusing, we end up getting explicit about how things are done, with loads of little remarks in totally unrelated help-patches.... i'm thinking of all these `click =>` and `open subpatch to see...`  and `Dealing_with_$0` repetitions).

and then, there is the sad fact that all theming has the apparent property of getting stale quickly. what looks cool today looks like 50ies SciFi tomorrow.


anyhow, just my 2¢. if you feel the necessity to go ahead, just do it.

**Comment by porres** [comment]
I'm sitting on this, the ideal situation for me would be adding a new functionality to canvases like I suggested in https://github.com/pure-data/pure-data/issues/1833
