### ISSUE TITLE
stop creating PRs for every commit?

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pddp#181]
don't know where to put this, but... now that we have #175 in place, I see that the history of the `documentation` branch becomes like this:

![documentation-branch](https://github.com/pure-data/pddp/assets/214034/ba9707bf-c444-4977-a924-3d653fad4896)

i figure, you don't ever look at the commit history, but I do regularly and it is a real eye sore.

so: can we avoid this?

- @porres could just directly push to the `documentation` branch in the pure-data repository (and completely drop the `porres/Documentation` branch).
  e.g. assuming that the `puredata` remote points to https://github.com/pure-data/pure-data/
   ```sh
   git push -u puredata documentation
   ```

 - you could also push to both branches, if you prefer this (but as it is a more complicated setup, it might as well go more wrong)
   ```sh
   git push origin Documentation
   git push puredata documentation
   ```

- if you insist on merging via the webinterface, you could
  - accumulate more commits before merging
  - always use `Rebase and merge` for merging to keep the history linear

when setting up the branch rules for the `documentation` branch I was tempted to add `Force a linear history` to the rules, but i thought that that would create more problems when a couple of people work together (and it seems overly pedantic anyhow).
rethinking, it's probably not a bad idea anyhow, since any *trivial* `merge` can be easily turned into a `rebase`, and any *non-trivial* merge won't work for Pd-patches anyhow.

--- 

for reference: here's how I would have imagined the history to look like
![documentation-branch2](https://github.com/pure-data/pddp/assets/214034/ce3a5b5f-542d-4e1b-807d-d19d2315c2b7)

**Comment by umlaeute** [comment]
with no dissents, i've now applied the rule to force "linear history".

please let me know if this creates any problems.

**Comment by porres** [comment]
> @porres could just directly push to the documentation branch in the pure-data repository (and completely drop the porres/Documentation branch).

sure, I'l ltry next time

> if you insist on merging via the webinterface, you could
> 
> accumulate more commits before merging
> always use Rebase and merge for merging to keep the history linear

I am quite used to using 'github desktop' and the web interface, I can also try to "Rebase and merge"

> with no dissents, i've now applied the rule to force "linear history", for solving the "spiderweb history".
> 
> please let me know if this creates any problems.
> 
> the "useless PRs" are not tackled at all.

hmmm, so, I just keep doing what I was doing then? :)

**Comment by umlaeute** [comment]
> hmmm, so, I just keep doing what I was doing then? :)

you shouldn't have to care about the "Rebase and Merge" anymore, as (I think) the only option fr you to merge is now exactly that.

but since this issue is really about "stop creating PRs for every commit", you still should push directly to the `documentation` branch, and not create an extra PR (for merging your changes into the `documentation` branch) *at all*.
(we will need to create a new *Documentation fixes* PR once `documentation` got merged, just like with the *stable development branch*; but that is a single PR until miller merges it)

**Comment by porres** [comment]
I just tried another commit and it seems I did it again, right?

I had the impression things would just magically work now

**Comment by umlaeute** [comment]
Depends on what you mean by "it" (and I'm currently afk so I don't want to do a full analysis of the situation).

Anyhow, you can push whatever you like to your own branches and nobody cares how you call these branches. It is only important that whatever you want to go into the `documentation` branch of the pure-data repository is pushed to the `documentation` branch of the pure-data repository (and *you* can and should push directly without doing any PRs)

**Comment by porres** [comment]
> Depends on what you mean by "it"

I think I created a new PRs for a new commit (and also every future one if I keep doing the same), didn't I?

**Comment by porres** [comment]
> didn't I?

Just did another pull but paying attention now, seems I'm, looks like I'm doing more PRs for sure...

>  It is only important that whatever you want to go into the documentation branch of the pure-data repository is pushed to the documentation branch of the pure-data repository (and you can and should push directly without doing any PRs)

I do have a local 'documentation' branch in my fork and I do target the documentation branch of the pure-data repository...

![Screen Shot 2024-01-05 at 12 58 34](https://github.com/pure-data/pddp/assets/5360142/651e6a99-7ff9-4bb8-a206-22bd363f591c)

and it only shows me an option to create a pull request

> (and you can and should push directly without doing any PRs)

i wouldn't know how, I am of course using the github desktop app and the web resources, maybe you mean I can do it via some command line in the terminal. After I click the PR button I go to the web and it only shows me how to create a PR

Then I can "squash and merge" 


![Screen Shot 20
![Screen Shot 2024-01-05 at 12 59 49](https://github.com/pure-data/pddp/assets/5360142/f0fee3d5-2b64-4c1d-ba23-e561cc6f6ad2)
24-01-05 at 12 59 30](https://github.com/pure-data/pddp/assets/5360142/dcab58c5-8cf6-4e93-8bf8-cb61a8cca89e)

If this is not good, let me know please

**Comment by Lucarda** [comment]
someone must correct me if i got it wrong but basically you have to:

- clone `https://github.com/pure-data/pure-data.git` i mean the official one and not your fork.

- checkout the `documentation` branch.

  - here you can `fetch`, `pull` or `push`
  
  - if anyone (like me) sends you a PR on the web just merge it. Then `fetch` and `pull` to update your "local branch".
  
  - if you edit files just `commit` and `push`. You have **write access** to `documentation` (like when you are committing to your `ELSE` repo).

**Comment by porres** [comment]
ok, now that I am part of pure-data, I was able to clone directly from pd repo and not my fork

I did a small test change in https://github.com/pure-data/pure-data/pull/2147/commits/570be229473828253961a77db5b57c5d560cc7c9 and pushed it, no PR, couldn't be easier, thanks!

**Comment by porres** [comment]
I'm just doing what I usually do in the github app like I do with ELSE, no brainer... sorry for not figuring out sooner and thanks again
