### ISSUE TITLE
What about dynamic patching? should we document it?

### ISSUE THREAD

**Issue by abreubacelar** [pure-data/pddp#19]
hello, i am helping porres creating the "reference" subpatches, and while i was writing the send-receive one, i remembered that [send] can send message to a named patch (with namecanvas). I know that this is complicated, and dynamic patching isn't officially supported, but even namecanvas helpfile has an example of how to do dynamic patching (it teaches you how to create a message in that patch, and open the curiosity of the user...)

maybe we should document it, but giving an alert for the user that any method involved may break in future releases? (as it isn't a feature that guarantees backwards compatibility)

**Comment by porres** [comment]
seems like a new section to the manual... and maybe a tutorial...

**Comment by porres** [comment]
closing as I added this to here https://github.com/pure-data/pddp/issues/14
