### ISSUE TITLE
General issues about redesign Pd Official Documentation

### ISSUE THREAD

**Issue by emviveros** [pure-data/pddp#2]
This issue is related to an effort in create a pattern design for Pd Documentation. The initiative is started because [Documentation Rework issue](https://github.com/pure-data/pure-data/issues/1300#) started by @barnabywalters.

To centralize the issues here I rewrite below some discussions that have already started that I thought were important:

[@emviveros says](https://github.com/pure-data/pure-data/issues/1300#issuecomment-845096041)
>Particularly I think the @barnabywalters idea of start to discuss a unified new model of documentation can be helpful. It doesn't have to be done in a hurry and updating little things in documentation as Porres has been doing is necessary to make Pd better for new users right now. But despite @porres' efforts, we still need better documentation.
>
>If we are able to reach a consensus on the best way to document Pd things, the work of creating documentation should be much lighter for everyone, in addition to making life easier for those using the documentation, since navigating in the help patch will always be similar.
>
>I suggest:
>
>1. start by answering what is the profile of the Pd user and what he needs within the documentation. Who knows we can start a topic on the Pd list. There are many Pd teachers, and users of course, who can provide very useful insights.
>
>2. With this information in mind, start thinking about an organization that contemplates the maximum possibilities raised in the previous step. It is possible that we need to create specific online documentation on the Pd page, which has as a positive point the possibility of translation into multi-languages.
>
>3. Document.

[@porres says](https://github.com/pure-data/pure-data/issues/1300#issuecomment-846441019)
>@emviveros I agree that bringing this to the Pd list can be better to have more input.

[@umlaeute says](https://github.com/pure-data/pure-data/issues/1300#issuecomment-846614084)
>you might start by not assuming that "the Pd user" is a white male academic.

[@emviveros answered](https://github.com/pure-data/pure-data/issues/1300#issuecomment-846658973)
>hahahaha!! Yes! Please!!! Maybe we have to extend the answering to Pd Facebook Groups. Maybe there we can expand the scope of the research.
>
>Looking for documentation of softwares created by people who do not understand themselves in the scope of white academic men can be another possibility.

**Comment by porres** [comment]
Sorry everyone, this thread is just too crazy and not objective, so I'm closing it. Some of the things discussed here are already happening and moved to other threads, so if you feel you want to give attention to something that was brought up here, please create a new dedicated issue
