### ISSUE TITLE
fix documentation on updating instances of an abstraction

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pddp#200]
in https://github.com/pure-data/pure-data/blob/c4fbe915bea799733f8b1d0a21210e82a7b435fd/doc/1.manual/x2.htm#L2080-L2081 it says:

>  In Pd, to make current all instances of the abstraction, either delete and recreate them or close and open the patch; this is done automatically in MAX. 

which strikes me as factually wrong.

**Comment by porres** [comment]
yes, there's a lot in this section that needs fact checking, revision and update to modern days and I have it listed at first in https://github.com/pure-data/pddp/issues/197

for the record, I didn't write this and I guess this is noise that has been there forever from a distant day when that it was true?

**Comment by ben-wes** [comment]
i think, we can just remove this line?
(doing so in my last PR towards your branch, @porres)

**Comment by porres** [comment]
> i think, we can just remove this line?

or comment out for now, like I did with some other paragraph just before

**Comment by umlaeute** [comment]
hmm, i think we have an established way to "make current all instances": save any instance of the abstraction (the rest will be automatically synced to the latest save, and as a side effect the other instances will lose all state).

i think that should be documented, rather than commented out.

**Comment by porres** [comment]
> i think that should be documented, rather than commented out.

hmmm, can you elaborate a paragraph for it, or a draft? mybe @ben-wes can include it

**Comment by ben-wes** [comment]
@porres imho, you already took care of this here:
https://github.com/pure-data/pure-data/blob/627dd911186daa0ea9b7502e2b15d6b4c20d4b8e/doc/1.manual/x2.htm#L1562

maybe this could be rephrased a bit - how about:

> You can create multiple instances of [abstraction1] or invoke it from different patches. Any changes made and saved to the contents of [abstraction1] will impact all of its instances (also resetting their state).

... now i'm not familiar with the behaviour of max, but i think, it should be fine to remove those lines in that paragraph comparing pd and max? any objections, @umlaeute ?

**Comment by ben-wes** [comment]
> that is not really "me" :) don't always assume I wrote the whole manual from scratch ;)

true. sorry. this was added by miller at least 17 years old:
https://github.com/pure-data/pure-data/blame/c4b07174787365fab838118650a8f06272da93a1/doc/1.manual/x2.htm#L905
