### ISSUE TITLE
4.data.structures/09.sequencer.pd regression bug in 0.55 test

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#210]
old discussion in https://github.com/pure-data/pddp/issues/208

as pointed by @maftkd, this example is basically ruined in the 0.55 test release (thanks so much for catching this up!). I had attempted to simplify the [voice] abstraction and remove a seemingly unnecessary [send] and [receive] pair inside the [pd sequence] abstraction, but they acted as a global variable sharing between all instances. Earlier last versions weren't really significantly compromised, but the current adaptation of the example with [clone] wasn't really correct or elegant either.

The [pd sequence] should be outside of the [voice] abstraction for things to work correctly and in a more elegant way, as should have happened before.

The manual must be updated to carry new screenshots and text adaptation

**Comment by porres** [comment]
done with https://github.com/pure-data/pure-data/pull/2308/commits/45c6406c4da15e224b8d55415314ae66fdbb178c

**Comment by maftkd** [comment]
Thank you @porres!
