### ISSUE TITLE
use $0 in example abstractions

### ISSUE THREAD

**Issue by sebshader** [pure-data/pddp#218]
The example I just came across is [adsr] from the audio examples.. A beginner had taken this example from the concept called an 'abstraction' that was supposed to abstract.. and was left with a mess when they tried to use it for polyphony because the [s line] doesn't use $0. (so sends to every other instance of course)

**Comment by porres** [comment]
sorry ,I don't really get it

**Comment by porres** [comment]
I'm closing this cause I don't get it and it seems there is a mistake

you seem to ask for [adsr] to use $0, but it already uses it, see image below

![Screen Shot 2024-06-08 at 01 26 44](https://github.com/pure-data/pddp/assets/5360142/768fe2c9-f30e-43a4-86c3-490c5ba7bbba)

**Comment by sebshader** [comment]
ok, it was only changed 2 months ago. sorry I should have checked first
