### ISSUE TITLE
standardize playing files for audio examples and revise methods

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#230]
We have some rather complicated examples in the audio tutorial sections that make use of two distinct approaches to play samples, for no real good reason, like, some use [pahsor~] into [tabread4~] and others use [line~] being driven by [metro] for looping.

These two methods introduced for looping, but for more sophisticated techniques than simply playing the sample in a loop.

For simply playing test files in a patch that is supposed to explain, say, FFT and stuff, we could simply use [tabplay~] that does the exact same job, without any sophistication. It would simplify and standardize things.

**Comment by porres** [comment]
I see that the advantage of using the [line~] and [tabread4~] method is that you can easily have Pd running in a different Sample Rate than the one from the sample...

On the other hand, I don't think that is very common, and the examples should be clear about that

**Comment by umlaeute** [comment]
> On the other hand, I don't think that is very common, and the examples should be clear about that

i'm pretty sure it is rather common.

e.g. on linux, pipewire is taking over JACK, and the default samplerate for pipewrite is 48kHz.

**Comment by porres** [comment]
> e.g. on linux, pipewire is taking over JACK, and the default samplerate for pipewrite is 48kHz.

So, just to be clear, is the default SR for Linux 48Khz, or Linux users just usually set the default SR to 48Khz? In any case, I can see the need for this in order to play the samples from Pd's example.

Anyway, what we should do then, and we're not doing that yet, is to use the file's sample rate, and keep using the [line~] method just in case people choose another SR or even try to load other files with a different SR. This is actually addressed in this other issue https://github.com/pure-data/pddp/issues/148

I will take care of that now and not adapt examples to use [tabplay~] instead, then.

**Comment by millerpuckette** [comment]
Default is 44100 everywhere, and I'm proposing changing it to 48000 
everywhere :)

M

**Comment by porres** [comment]
I reopened and changed the subject, but I'm not if I should have opened a new issue or if I should have reopened it at all!

Anyway, idea is to keep this opened as a note for me to revise the examples regarding playing samples and making it clearer that one can use [tabplay~] if the sample matches Pd's sample rate and that the other examples. I'm not really sure, just keeping it opened until I have a clearer idea of what make of this.

**Comment by porres** [comment]
For reference and a personal note I found [tabplay~] used in 'G01'.

This would be a problem is one is using Pd in 48Khz and stuff.

**Comment by porres** [comment]
A good idea for all, or at least most of the examples that uses samples as a test sound is to allow the user to choose a file with a bang into [openpanel] as well.

**Comment by porres** [comment]
ok, i rebooted it all into a new issue https://github.com/pure-data/pddp/issues/232

**Comment by umlaeute** [comment]
> So, just to be clear, is the default SR for Linux 48Khz, or Linux users just usually set the default SR to 48Khz?

the default samplerate of a specific audio server (pipewire) is 48kHz, even if the soundcard runs on something else (e.g. 44.1kHz).
pipewire is becoming the de-facto standard for desktop linux, replacing both PulseAudio (for the media-consuming lay audience) and JACK (for the pro-audio people).

it's "rather complicated" to change the samplerate for pipewire, which means that mostly people will end up with an 48kHz sr and no clue how to change it.
(i's totally possible; but it's more convoluted than going to Pd's preferences and selecting a different sr).
