### ISSUE TITLE
help file, about 1.poly.synth.pd

### ISSUE THREAD

**Issue by marcl-dot** [pure-data/pddp#251]
@porres,
Hi, as a proposal....
so I just reorganized gadsr.pd
In synthvoice.pd, changed the first 3 outlets from “unpack » to gadsr.pd
In synth.pd, reintroduced “moses 1e+06” on the 3rd poly outlet, then modified the pack inlets, 

The sound seems more “correct” to me 
see attachment
[Archive.zip](https://github.com/user-attachments/files/17266725/Archive.zip)

and I wonder if it is not interesting to reintroduce the mtof table to have a visualization on the response curve for "educational purposes"...

Cheers

**Comment by porres** [comment]
I don't understand what you are trying to fix and change, can you be more specific?

I can't see why [moses 1e+06] is needed, why do you want that?

**Comment by porres** [comment]
Hi, I'm closing this as this is not a real issue, please reboot it. You can open a new issue where we can discuss what is wrong with the patch and what to do about it, and you can propose a new patch via a PR that closes the issue. Can you reboot this please?
