### ISSUE TITLE
How to send PRs to the html docs?

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pddp#252]
@porres the readme says that PRs should target to https://github.com/porres/pure-data/tree/Documentation which seems to not exist.

If i target to https://github.com/pure-data/pure-data/tree/documentation i get: `This branch is 190 commits behind master.`

**Comment by porres** [comment]
> the readme says that PRs should target to https://github.com/porres/pure-data/tree/Documentation which seems to not exist.

yeah, it doesn't

> If i target to https://github.com/pure-data/pure-data/tree/documentation i get: This branch is 190 commits behind master.

that's the one we should actually refer to in theory, but the thing is that I was just having too much problems keeping things in sync and asked @umlaeute multiple times about being able to do that, to the point I just gave up and kept doing PRs in my own branch instead.

For now I think I can restore the https://github.com/porres/pure-data/tree/Documentation but I'm using a different one right now, see https://github.com/pure-data/pure-data/pull/2434

**Comment by Lucarda** [comment]
ok done via https://github.com/porres/pure-data/pull/84

closing this issue.

**Comment by porres** [comment]
ok, thanks
