### ISSUE TITLE
document list method to objects with a single inlet, where it gets accepted and truncated to the first value

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#253]
number and symbol boxes can take lists, where it trunctaes to the 1st element, and this is not documented

**Comment by umlaeute** [comment]
is this different from any other object that has a float xor symbol inlet?
does it need to 
and if not, isn't this already documented (e.g. 2.control.examples/04.messages.pd)

**Comment by porres** [comment]
Ok, so indeed we have an issue. For consistency reasons, I can't document this in gui boxes but ignore in iemguis... 

On the other hand, if there is some sort of hidden and golden rule on how an object with a single inlet behaves with list input, this must be clear somewhere.

I'm now looking for other objects besides the iemguis and the first I see is [makefilename] that also works that way... so, yeah, there is some sort of hidden and golden rule :) 

[tabread] follows suit, so does:
[expr]
[abs] and other unary operators and trigonometric functions
[mtof] and other accoustic conversion 

and I might be missing others, anyway, I must revert the changes and document this 'rule' somewhere

**Comment by millerpuckette** [comment]
I would suggest a pointer to one common location where it's explained 
how floats, lists, symbols, and bangs are treated by inlets.  (I think 
this is in the "theory of operation" already, no?) - otherwise you're 
copying the same info to over 100 help files.

cheers

Miller

**Comment by porres** [comment]
thinking properly about this, it is in fact the same rule of distributing the list to multiple intlets... but we just have a single inlet :) 

well, will try to make this clearer!

**Comment by porres** [comment]
the control tutorial example 04.messages has wrong information where it says that lists get distributed ONLY if the object has more than one inlet... so it needs to be fixed.

Also, there's a section in the manual about this ("2.7.4. Inlets and lists") and we need to improve and also take care there .

I also mean to have an abstraction to include in all reference subpatches with a guide and information on how to read the reference information that would also treat this issue. See https://github.com/pure-data/pddp/issues/96
