### ISSUE TITLE
Add Pd-ceammc to featured downloads in puredata.info

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#34]
previous discussion in https://github.com/pure-data/pddp/issues/33

**Comment by umlaeute** [comment]
to answer the question that was raised in https://github.com/pure-data/pddp/issues/33#issuecomment-976334139 : 

i think the main criterion for adding something to the "featured downloads" is how many people are actually looking for it on puredata.info.

this relates to how many people are actually using it:
- is there a community?
- is https://puredata.info the place were people that want to become members of this community start looking?

and of course: do the maintainers of a project actually feel like getting on the "featured downloads" page.
(it's not like @uliss or @njazz ever raised the issue)...

**Comment by porres** [comment]
closing in favor of discussion in https://github.com/pure-data/pddp/discussions/42
