### ISSUE TITLE
standardize 'compatibility' documentation

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#36]
some help files explicitly show the message, some do not, let's make them all show.

**Comment by umlaeute** [comment]
you mean "all" help patches that document objects where `compatibility` has an effect?
or *all* help patches?

**Comment by porres** [comment]
"all" help patches that document objects where compatibility has an effect. It doesn't hurt to explicitly put a message box there. Sometimes it's just too hidden into the text. Like we just had a change with bob~, if I open the help file, it's hard to notice it had a compatibility change without the message to call my attention.

**Comment by porres** [comment]
objects that document this are:
- [clone]
- [declare]
- [hip~]
- [hradio]/[hslider]/[vradio]/[vslider][my_canvas]/[toggle]/[vu]
- [inlet~]
- [line]
- [wrap~]


list them in pd-messages.pd

**Comment by porres** [comment]
missing explicit use: [clone], [bob~], [declare]
