### ISSUE TITLE
Pd Manual issues and revisions

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#4]
This thread is to point out issues with Pd's Manual => https://github.com/pure-data/pure-data/tree/master/doc/1.manual

One issue is that I think that document can be renamed as Manual only - see a related issue https://github.com/pure-data/pddp/issues/13

We can add another section to the help menu, like a  'Welcome to Pd' section, with general information about 'documentation', taken from the 'overview' section of Pd's Manual.

Below 'Welcome to Pd' we can have the actual 'manual'.

Some of the discussion here is based on the discussion in https://github.com/pure-data/pure-data/issues/1320 by the way...

So, now that I have this reorganizing idea and issue, I'll move on to the next comment where I'll actually talk about the issues with the contents of the 'manual' itself, and we can use this thread to find issues on it.

**Comment by porres** [comment]
in x_1.html - "To get started writing your own C extensions, refer to chapter 4 of this manual."; not quite accurate, not sure about this. "You can check puredata.info/docs/BooksAboutPd/." seems a bit out of place. All the noise about 'GEM' is also a bit too much...

------------------------

in 'x2' 2.1 overview - it also says GEM has no parallel in MAX (not true).

note change help 'canvases'

"Pd's printout appears on the main "Pd" window, unless you redirect it elsewhere." - where elewhere and how?

feature, add atom box as object

midi synth figure is outdated [osc~ 0]

 (and not a "note off", t <= close parenthesis

better explain "control" vs "tilde"

"Certain data-storage objects have functions for reading and writing other files to save and restore their internal state." <=. mention [savestate].

document intelligent patching

"If there's more than a small amount of text (in a comment, for example) you might want to select the text and choose "text editor" from the Edit menu" - there's no such thing!

2.3 - "In Pd, objects intercommunicate by sending messages" (a.k.a. 'control data').

2.3. messages (add to help file of message box).

Also, the special object "pd" is defined to which you may send messages to start and stop DSP. - add "and others", also addd manual section for all pd messages.
soundfiler, readsf, and writesf objects. <= add tilde to writesf~ and readsf~

 whose names conventionally end in a tilde character to warn you what they are. (SINUSOID)

hen this linear list is run down in blocks of 64 samples each; at 44100 Hz (**BY DEFAULT**). (**T**)this means the audio network runs every 1.45 milliseconds.

"Inlets or outlets are configured in Pd either for messages or audio; it's an error to connect an audio outlet to a non-audio inlet or vice versa" Not Actually **vice-versa**!

If there are loops, you will see the error message at "sort time." <= specify all errors and explain more...

You can build algorithms with feedback using nonlocal signal connections. <= explain more / add SEE "2.4.5. nonlocal signal connections"

Your subpatches  <= ADD 'SEE SECTION 2.7"

If you want to use a control value as a signal, you can use the sig~  <= document how sig~ is mostly unuseful these days!!!

2.4.4. switching and blocking <= add to block~ help file (rename block help file)

it acts on the entire window and all of its subwindows => SEE SUBPATCHC SECTION

At the (untested) extreme, <= it's been tested!

your own recursive filters => ONE SAMPLE FEEDBACK... for things like recursive filters and more?

add 2.4.5. nonlocal signal connections to help files

The only way to ensure this is to create the delread~ after you created the delwrite~; if things get out of whack, just delete and re-create the delread~. <= Document order of execution!!!

**Comment by Lucarda** [comment]
> "Pd's printout appears on the main "Pd" window, unless you redirect it elsewhere." - where elewhere and how?

./pd -stderr

> midi synth figure is outdated [osc~ 0]

whats the problem with that. 
If there are problems with images use Debian/LXQT to stay in sync with the other screen-shots (not strictly necessary, of course).

**Comment by porres** [comment]
> from a terminal:

where is this documented?

> whats the problem with that?.

long long long ago if you wanted to have osc~ take control data instead of signals you shouldd specify a float argument... this is not the case now and the argument here is not necessary, it'd be better if we had a figure without the argument!

**Comment by Lucarda** [comment]
> where is this documented?

https://github.com/pure-data/pure-data/blob/master/doc/1.manual/x3.htm#L592

**Comment by porres** [comment]
I was hoping for more details :) maybe we can add? ;)

**Comment by Lucarda** [comment]
> midi synth figure is outdated [osc~ 0]

> (and not a "note off", t <= close parenthesis

if you upload a pd patch here i can easily update the image on PR  #1460

**Comment by porres** [comment]
[fig.pd.zip](https://github.com/pure-data/pddp/files/7571539/fig.pd.zip)

**Comment by porres** [comment]
section 4: improve how objects are loaded, how you can override internals...

**Comment by Lucarda** [comment]
> fig.pd.zip

Now included in PR #1460
