### ISSUE TITLE
a tutorial for internal messages 

### ISSUE THREAD

**Issue by fdch** [pure-data/pddp#40]
There has been some improvements and discussions on dynamic patching lately and I would like to share a personal guide on how I managed to work with internal messages a couple of years ago, partly using existing information from puredata.info and from the `g_*.c` files. Perhaps this could be useful to tidy up with better instructions on what to do and what not to do. 

https://github.com/fdch/pd-messages

> > I think it would be good to have some sort of guidelines help patch for this in the manual. 

> I'm up for that. I've been actually working on something like this in https://github.com/porres/Live-Electronic-Music-Tutorial - but it's not icluded yet, will be in the next version!

> _Originally posted by @porres in https://github.com/pure-data/pure-data/issues/623#issuecomment-491453716_

**Comment by umlaeute** [comment]
i've taken the liberty to just transfer the issue (instead of closing the original one, and opening a new one here)

**Comment by fdch** [comment]
I updated the url on my original post. I moved the tutorial I made back then to its own repository.

The tutorial itself needs an update, considering pd changed quite a lot since then, and perhaps some cleanup.

Thanks to @porres and @umlaeute for keeping this post going.

**Comment by porres** [comment]
hey, I can't get yout main.pd example to open or work...

**Comment by porres** [comment]
and it seems you just have a tutorial with examples, as far as documenting the messages, I'm thiking of something simpler, like extended used to have i 'pd-msg'

**Comment by porres** [comment]
I already have added some pd messages documented in https://github.com/porres/pure-data/tree/Documentation see 'pd-messages.pd'

I just need to add to it "messages to the patch" and document some basic things we need for dynamic patching (clear patch, add objects, connect stuff).  I close this for an issue just for that. https://github.com/pure-data/pddp/issues/44

**Comment by fdch** [comment]
> hey, I can't get yout main.pd example to open or work...

Can you please elaborate on this? Did you get any errors on console? I appreciate the feedback :)

**Comment by porres** [comment]
sure, patch simply didn't open :/ pretty weird!

**Comment by fdch** [comment]
@porres, I know you've given pd-messages a nice doc section. I have fixed the issue with my patch, so give it a go if you have the time, you might catch a few more undocumented messages over there.
