### ISSUE TITLE
puredata.info feature request, show downloads by category also in chronological order

### ISSUE THREAD

**Issue by abreubacelar** [pure-data/pddp#48]
i don't know if this is the correct place, but since there are related posts about puredata.info here i feel that i could ask about that...

i saw iohannes comment on https://github.com/pure-data/pddp/issues/1#issuecomment-977865058 that you can see all pd flavours/forks alphabetically in this link https://puredata.info/downloads/by-category/distribution

navigating the downloads section on puredata.info, i saw that is also possible to get lists alphabetically of all the other categories, but i didn't saw how to get them in a chronological order (maybe just from newest, i don't know if list from the oldest would be useful)... you can see the newest ones in https://puredata.info/downloads but not get a full list per category... is this possible/viable?

**Comment by porres** [comment]
> is this possible/viable?

I have no idea, ping @umlaeute / @Lucarda

**Comment by porres** [comment]
I'm gonna say it's probably possible, but the thing is, let's be honest, this request hasn't triggered any real interest even in responding to this answer...

can I close this @abreubacelar ? 

I would also reason that nowadays people check downloads from deken, which kinda sorts things from newest release/download to last. Same for distributions where newest versions are featured... so maybe this is not necessary I guess. 

Im just gonna close this but if you think I'm wrong and have a counter argument for the request, please feel free to reopen this
