### ISSUE TITLE
check formatting of section 4.5 on manual on pd-0.52-0test3

### ISSUE THREAD

**Issue by abreubacelar** [pure-data/pddp#50]
i just downloaded pd-0.52-0test3, and checking the manual, section 4.5. (Search order for loading objects), is all in bold, and this bold extends until the links in the end of the page, is this ok?

**Comment by porres** [comment]
@Lucarda, you fixed this already, right?

**Comment by Lucarda** [comment]
Yep, https://github.com/pure-data/pure-data/pull/1496 (not yet merged)

**Comment by porres** [comment]
merged
