### ISSUE TITLE
pd-messages on namecanvas helpfile is unreachable, pd-0.52-0test3

### ISSUE THREAD

**Issue by abreubacelar** [pure-data/pddp#51]
i see there is a Pd-message.pd file on the folder, so maybe the abstraction is misnamed?  see the image

![Captura de tela de 2021-12-13 19-54-41](https://user-images.githubusercontent.com/16086370/145907868-57a89ae3-b7e8-4c2f-9317-295a3ba937b8.png)

**Comment by porres** [comment]
if you use "P" insead of "p", does it load?

**Comment by abreubacelar** [comment]
yes, i think the problem is that pd on linux and windows are case sensitive, but on mac not...

**Comment by abreubacelar** [comment]
but also notice, that just changing "pd-messages" to "Pd-messages" is an incomplete solution, because you also need to change [s pd-pd-messages.pd] to [s pd-Pd-messages.pd]...

**Comment by umlaeute** [comment]
wouldn't it be better to lowercase the filename instead?

i think it is general best to avoid all capitalisation in objectclasses, as it is just too easy  to break things. (as has been shown in this prime example).

**Comment by umlaeute** [comment]
@abreubacelar btw, case sensitiveness is not really a property of an operating system, but rather of the file system.
- NTFS (as is predominant in the Windows world) is *case-**in**sensitive*
- ext4 (and most other predominant filesystems that are used in the Linux world) as *case-sensitive*
- APFS (on macOS) can be both, but the default is *case-**in**sensitive*
