### ISSUE TITLE
Slider help patch would benefit from reminder that pixel size of slider affects output resolution

### ISSUE THREAD

**Issue by helmutaab** [pure-data/pddp#56]

**Comment by umlaeute** [comment]
could you elaborate on what you mean?

the output resolution of my screen does not change if change the pixel size of a slider in Pd.

**Comment by helmutaab** [comment]
While a vertical sliders size is 127 pixels, and it's range is set to 0 to
127, then it outputs 127 values with a step size of 127/127 across its
range. When reducing the maximum range value to 100 pixels, it outputs 100
values (without using Shift key). This means that output value steps are
127/100, not 100/100 as expected without taking into account the sliders
mechanism.

**Comment by umlaeute** [comment]
ah.

i thought i would have been obvious from the mere existance of the `[pd example-discrete]` that the sliders do not output discrete values. e.g. if you set the range as `0..1` you probably wouldn't expect the value steps to be `1/1`.

could you suggest a better wording?
i would very much prefer it if "pixels" would not be mentioned at all.
instead something how the values are "evenly spread" across the size of the slider.

**Comment by helmutaab** [comment]
Ha!, Yes, forgive me for not spending more time understanding that before
opening my mouth. I did expect value steps to be 1/1 of over range.

Still, perhaps a comment in the example-discreet, that to get more discreet
steps than Width/Height is not possible without using the Shift key, could
clarify this.

My current use case: using slider as (dynamically growing in range) high
density V/Hradio.
Why? Much easier to sea with poor eyes than number box on busy patch.

Thank you for your response and work

**Comment by porres** [comment]
yeah, it all seems very obvious to me too... so I dunno how to clarify this or how it can be confusing or misleading. Maybe because number boxes do increment in integers?

**Comment by helmutaab** [comment]
The mouse over a number box requires the same travel accross the screen to
generate as many steps, so, without looking at the source, it appears that
the mechanism is identical.

It is no longer a mystery to me, put it down to an aging and buckled
synapse, and thanks for giving it your attention.

**Comment by porres** [comment]
I guess something like "values are "evenly spread" across the size of the slider" may be useful, let me see what I can do.

**Comment by helmutaab** [comment]
Great! Thanks
