### ISSUE TITLE
Revise help file of 'acoustic conversions'

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#59]
I spotted a mistake where it says zero dB corresponds to 0.0001, it's actually 0.00001 (1e-05).

I think we could also add more information that Pd uses an arbitrary dB scale and not 'dBFS'

**Comment by umlaeute** [comment]
it's `dBFS` with an offset of 100 (and clipped/clamped at <=0)

**Comment by porres** [comment]
this is a good explanation/remark, I'll revise it.
