### ISSUE TITLE
Help files redesign (including a 'reference' subpatch)

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#6]
In https://github.com/pure-data/pure-data/issues/1320 we were discussing a new design format that would include a quick reference subpatch, much like in use in other documentation templates for Pd out there.

Here's a first draft: 

<img width="1175" alt="Screen Shot 2021-05-29 at 17 26 35" src="https://user-images.githubusercontent.com/5360142/120083994-0fab0300-c0a3-11eb-9f63-ff382b837894.png">

There's also the plan to provide such help files and references as html files distributed with Pd and making them available on the internet as well. They would live in '8.topics' where we already have html for slop~ and could be renamed to 'reference'

**Comment by umlaeute** [comment]
1. i think the implication of this issue title is that "we don't have a reference" which i think is just plain wrong (we do have a reference, in `doc/5.reference/`. you might not like how it looks or what it contains (though you didn't mention that if you do), but that doesn't make it less of a reference
2. i don't see how the new proposed HTML-files would be *more* a reference. so renaming the folders would only add confusion for now apparent gain.
3. afaict, the `8.topics` folder is quite the opposite of a "reference" - it is an elaborate technical explanation of specific use-cases.
   - i agree that **topics** is a bad name though. (`8.directory` might have been as good)
   - heck we could also rename the `6.externs` folder to `6.reference` :stuck_out_tongue: 

anyhow, i think the actual folder-name is mostly bike-shedding. let's get some content first...

**Comment by porres** [comment]
I’ll keep this issue for just adding reference subpatches. Other ideas like having them as html references somewhere can be discussed on a new issue

**Comment by porres** [comment]
working on this here: https://github.com/porres/pure-data/tree/help-reference

**Comment by porres** [comment]
> working on this here: https://github.com/porres/pure-data/tree/help-reference

this is now done and part of => https://github.com/pure-data/pure-data/pull/1517
