### ISSUE TITLE
document '-ascii' flag in [pd~]?

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#60]
see https://github.com/pure-data/pure-data/blob/master/extra/pd~/pd~.c#L1136 ( looks like a bool which seems to control whether message passing is via binbuf or string)

"This -ascii flag asks pd~ to print messages and audio out in ascii so
that it's easier to debug.  Unfortunately this also causes loss of precision
so in practice one should always use the default, binary connection." Miller

**Comment by Spacechild1** [comment]
As I've written in the mailing list, I wouldn't bother documenting is. I don't see how the `-ascii` could actually help with debugging in practice... As Miller said, there is no reason to use anything other than the default binary mode.

**Comment by porres** [comment]
> As I've written in the mailing list, I wouldn't bother documenting is. I don't see how the -ascii could actually help with debugging in practice... As Miller said, there is no reason to use anything other than the default binary mode.

ok, closing this
