### ISSUE TITLE
document that DS arrays can only be represented visually in a discrete way

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#75]
Arrays can only be represented visually in a discrete way in accordance to the "Y units per pixel" value, but they can hold whatever value. Let's say the unit is "1". When you drag values up and down they jump in units of "1". You can set a value to be 31.999, but it is displayed in the same way as 31, it only moves up if you set it to 32. And if the value is set to, say 25.5, if you click and drag on the value it'll increase in units of "1" and keep the decimal value, so it can be 26.5, 27.5, whatever...

Anyway, this is somewhat mentioned in the sequencer example, but needs to be better explained.

**Comment by abreubacelar** [comment]
hmm.. this is wrong, the jump depends on the y units configuration, if you set it to -0.25 for example, the jumps will be in 0.25 steps (or am I wrong? if I am just ignore and delete this comment)

**Comment by porres** [comment]
> the jump depends on the y units configuration

that is what I said... **_Arrays can only be represented visually in a discrete way in accordance to the "Y units per pixel"_** the step defined as "y unit" is still a discrete step!

anyway, already tried to explain it.
