### ISSUE TITLE
document bang method to math operator objects.

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#8]
many math objects don't have a documented bang method, let's list them here...

**Comment by umlaeute** [comment]
wouldn't it make more sense to teach the users how this applies to many many objects, instead of repeating the entire thing again and again?

i mean, we don't explain what a `[bang(` is in each and every help-patch that uses it.

more to the point: we don't explain the hot/cold concept for each object that uses it. and a `[bang(` to the first list is just an extension of this concept - triggering the hot inlet without sending any data to it.

but of course we must make sure that people actually do read this documentation at least once (and the *operators-help.pd* might be a good place to do that).

also, i wonder why in  *operators-help.pd* the `bang` is sent to an otherwise useless `[f]` object.

**Comment by porres** [comment]
> wouldn't it make more sense to teach the users how this applies to many many objects, instead of repeating the entire thing again and again?

for this case it'd be only once, and it doesn't hurt to put an example there explicitly saying it works. Other objects that have a bang method like that are documented ([swap], [pack])... 

now, things like [mtof] don't have this bang method... so when are you to expect it? Best just to document when it happens.

**Comment by porres** [comment]
- more on this, [log] has a bang method, other objcts in math-help don't.

- [expr] also has a bang mthod

checking out more

**Comment by umlaeute** [comment]
> now, things like [mtof] don't have this bang method... so when are you to expect it? Best just to document when it happens.

whenever the object needs an internal state. that is: all binops (e.g. `[+]`, `[min]` and `[log]`)

the unop-objects don't need to maintain an internal state, so they also don't have a bang-method (like `[cos]`, `[abs]` or `[mtof]`)

that looks quite consistent to me.

`[makefilename]` and `[expr]` both need to maintain an internal state, so they have a `[bang(`-method.

**Comment by porres** [comment]
but [atan2] doesn't have it... should it be included then?

anyway, not that many help files to update. I can put the bang method example just for [log]... no need to have a separate help file just for it I think

**Comment by umlaeute** [comment]
> but [atan2] doesn't have it... should it be included then?

i think so.

**Comment by porres** [comment]
help, why is [pow] an 'arithmetic' binary operator, but 'log' is a 'math' function? Couldn't [log] be part of 'arithmetic' as well?

**Comment by porres** [comment]
> [makefilename] and [expr] both need to maintain an internal state, so they have a [bang(-method.

it seems [makefilename] has a pretty useless bang method as it doesn't really maintain an internal state, and I can't see why it should do that either.

**Comment by umlaeute** [comment]
> it seems [makefilename] has a pretty useless bang method as it doesn't really maintain an internal state, and I can't see why it should do that either.

so what's the format-string then, if not an internal state.

should we really get rid of it?

**Comment by porres** [comment]
> should we really get rid of it?

This is not documented and I can't see the use case... I don't see a problem in taking this out but at least I don't see the point of documenting it even if we keep it... (keep it then as an obscure and undocumented useless functionality).

**Comment by porres** [comment]
what is 'fixed-point' binary operators? This is the description in "otherbinops-help.pd". Are they really 'fixed-point' in a sense that they need to be described as such as opposed to the other arithmetic operators?

**Comment by umlaeute** [comment]
> > should we really get rid of it?
>
> This is not documented 

what are you talking about?

>  I can't see the use case

so?

> and undocumented useless functionality

what's useless?


> Are they really 'fixed-point' in a sense that they need to be described as such as opposed to the other arithmetic operators?

they are 'fixed point' as opposed to 'floating point' insofar as they use integer-arithmetic (aka fixed point arithmetic) internally.
it makes sense to mention that as a floating-point `[div]` would be quite different.

**Comment by porres** [comment]
> it makes sense to mention that, as a floating-point [div] would be quite different.
> however, they should probably be called "using integer arithmetic", as "fixed point arithmetic" is more general and could lead to some confusion.

But then, this is only true for [div] and [mod], right? What's confusing here is that [>] takes floats. So I don't think it's a good idea to generalize this in the header as if it were for all objects. Let's just specify this when it's pertinent. We can just have 'other binary operators' in the header.

**Comment by danomatika** [comment]
I think [div] and [mod] should be in operators-help.pd as they are not "binary operations."

**Comment by porres** [comment]
> I think [div] and [mod] should be in operators-help.pd as they are not "binary operations."

well, the header for operators-help.pd  says "binary arithmetic operators"

**Comment by danomatika** [comment]
I would argue that they should simply be referred to as "arithmetic operators." The term "binary arithmetic" may be technically correct, but I don't think it needs to be defined to that degree.

**Comment by porres** [comment]
> I would argue that they should simply be referred to as "arithmetic operators." The term "binary arithmetic" may be technically correct, but I don't think it needs to be defined to that degree.

ok, I'll do that, btw @danomatika, I asked about this before here... wouldn't log be an arithmetic operator as well? like [pow]?

**Comment by danomatika** [comment]
Furthermore, "otherbinops-help.pd" should maybe be "conditionalops-help.pd" or "relationalops-help.pd" as all of the objects, save [div] and [mod] (which should be moved), are conditional/relational comparison operators. Most programming languages refer to them as conditionals, ala C's `if(A == B) {do C}` etc.

**Comment by porres** [comment]
> Furthermore, "otherbinops-help.pd" should maybe be "conditionalops-help.pd" or "relationalops-help.pd"

what about just 'binops'? as opposed to "other"

> The help patch even opens with "Relational operations..."

it actually splits into 4 sections: 'Relational operators' (comparison), Logical operators, Bitwise operators, and then div/mod (Fixed-point binary operations?) that should be moved.

I guess 'binops' and arithmetic operators will sort this out...

**Comment by porres** [comment]
> what are you talking about?

the bang method of [makeflename] is not documented... in theory we don't really know about it. 

> so?

so it's useless

> what's useless?

something that has no use case, no reason to use it. I say either we store the input value into the object nd then bang calls it, otherwise, I don't think it's worth mentioning this (and I'd vote even to take this bang method out).

But anyway, I have changed the issue title and this now only deals with documenting the bang method for these mathematical operators.

I haven't changed the way atan2 works or swapped objects from help files. I'll first just document this bang method and do some minor changes to the help files of operators, otherbinops, math-functions and expr. I have also improved the 'see also section'.

**Comment by danomatika** [comment]
Without looking at the code, I imagine the makefilename “bang method” is not a separate function at all but simply the object’s list input handler dealing with a “bang” aka empty list. In this case, there is nothing to remove and the message itself has nothing to do internally with state. At most, an error could be added when receiving an empty list, but then again creating makefilename without arguments and then banging it with an empty list is useless but “wrong.”

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by porres** [comment]
there's an actual bang method code, s by removing the method, I meant to remove this whole section completely... https://github.com/pure-data/pure-data/blob/eeef4ba9130d3182146927c37fa57d61bbff0f0b/src/x_connective.c#L1391

it just defaults to '0' if the type format is a number, or to the format name if it is a symbol

**Comment by umlaeute** [comment]
so i finally checked the code, and yes the `[bang(` method is *not* about re-evaluating an internal state.

my conclusion is:
`[makefilename]` belongs to the [`printf()`](https://linux.die.net/man/3/printf) family of functions, just like `post()`.
all of them allow you to specify a format-string with placeholders.
that doesn't make using *no placeholders* useless. in fact, there are plenty of uses where e.g. `post()` is used without placehoders (e.g. [here](https://github.com/porres/pd-else/blob/4c9fb0f339d608196d63cb5aef87281262ff634f/Classes/Source/else.c#L38).

for the sake of consistency, i would therefore argue that there is absolutely no good reason to remove the empty list method (which i think is the context of the bang-method here).


> the bang method of `[makeflename]` is not documented... in theory we don't really know about it. [...] so it's useless

i think this is conflating to unrelated concepts. *undocumented* is entirely different from *useless*.

> I don't think it's worth mentioning this 

probably. i never argued that it ought to be documented.

**Comment by porres** [comment]
this was done
