### ISSUE TITLE
Miller's book HTML cosmetics.

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pddp#81]
@millerpuckette 

I had done some "cosmetics" updates to the HTML files from http://msp.ucsd.edu/techniques/latest/book-html.tgz.

It includes:

- upgrade to HTML5

- fixes to the navigation buttons

- support for small browser windows (smartphones tablets).

- some CSS styling.

the files are in repo: https://git.nubegris.com.ar/lucarda/miller-book

it can be cloned via: https://git.nubegris.com.ar/lucarda/miller-book.git

of course my idea is that you use this update on your server. 

let me know if this gets accepted and/or whatever.

:)

**Comment by porres** [comment]
@Lucarda ,  I see this doesn't require a PR, so... is @millerpuckette aware of this? :)

**Comment by porres** [comment]
> @Lucarda , I see this doesn't require a PR, so... is @millerpuckette aware of this? :)

pingin @Lucarda and @millerpuckette again. This doesn't seem to me like an issue that belongs here by the way. Can you solve this via private communication and can I close this?
