### ISSUE TITLE
typos in help-patches

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pddp#82]
bacslash bacslashes Smicolons blocck afterward backwarss canvas's cavas cosisting loaddbangs loadding logarthmic precisio recceive recciprocal speacially suprress trunctaed velocitty

**Comment by umlaeute** [comment]
there's also
- "band-pass", "bandpass" and "bandpasse" (not sure whether the last one is a typo; the other two are probably fine)
- "behaviour" vs "behavior" (both are correct, but we should standardize on a single spelling)

**Comment by porres** [comment]
about "afterward" --> https://thewordcounter.com/afterward-or-afterwards/

**Comment by porres** [comment]
the afterward/afterwards also relates to backward(s). Like "bandpass", we need to pick one, maybe without the 's' is more proper as it is more "american", like miller :)

**Comment by porres** [comment]
I can't find the "canvas's" typo...

**Comment by porres** [comment]
> I can't find the "canvas's" typo...

Probably I have already caught it and fixed in my documentation updates branch, same with "loaddbangs"

**Comment by porres** [comment]
will also go for 'Behavior' as it seems it's more "american"

**Comment by porres** [comment]
well, just went for backwards and afterwards, seems better to me...
