### ISSUE TITLE
[wip] html files

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pddp#9]
This issue (with its preview) tries to focus on what actually has to be done in a proper PR to the html files.

- reworks "Chapter 1"

  - more explicit explanation of the "doc" sub-folders.
  
  - warms of outdated FLOSS manuals.
  
- Changes in the CSS file (font, font-sizes, font-colors). 

- Includes proposed "Dark-Mode" theme CSS by @emviveros 

- Includes a javascript file allowing to toggle "Dark-Mode" theme and "sans serif" fonts.

- Updated images.

-----------------------------
https://lucarda.github.io/pd-manual-preview-1/ to preview.

note: might be needed to clear the browser's cache, at least "images and files" to see the updates.

**Comment by emviveros** [comment]
First, it's already very good. The color scheme already issue accessibility, continuing in this issue, provide a dark mode is very welcomed. My eyes, already a little old, are also grateful.

I modified your css with propositions in this sake and playing with serif to enhance readability.

[CSS_light_and_dark_modes.zip](https://github.com/pure-data/pddp/files/6703654/CSS_light_and_dark_modes.zip)

We need to consider favor images with bigger fonts like [2.7 subpatches](https://lucarda.github.io/pd-manual-preview-1/x2.htm#s7) 
![Captura de Tela 2021-06-23 às 13 58 16](https://user-images.githubusercontent.com/3089536/123138237-2d158780-d42b-11eb-8576-c94e98d0864f.png)

against images with little fonts like in [2.1.2 object boxes](https://lucarda.github.io/pd-manual-preview-1/x2.htm#s1.2)
![Captura de Tela 2021-06-23 às 13 58 01](https://user-images.githubusercontent.com/3089536/123138307-40285780-d42b-11eb-8dee-7aaba054673c.png)

**Comment by Lucarda** [comment]
I had injected your proposed CSSs to a single one with a Dark-Mode toggle.

The button is at top-left. I also added a TOC button.

See the preview on https://lucarda.github.io/pd-manual-preview-1/

I had merged this PR in my repo https://github.com/Lucarda/Lucarda.github.io/pull/1

:)

**Comment by Lucarda** [comment]
ping @emviveros 

https://lucarda.github.io/pd-manual-preview-1/ to preview.

note: might be needed to clear the browser's cache, at least "images and files" to see the updates.

**Comment by emviveros** [comment]
WOw... This think is quite good!

Other things I see:

1.  Resize automatically images to maintain layout in mobile:

![photo_2021-06-26 11 43 37](https://user-images.githubusercontent.com/3089536/123517441-532f6780-d677-11eb-95e4-6219af7377bf.jpeg)

2. That's doesn't a big issue, but what you think centralize block text on browser? It can make sense once the width in fixed?

Sorry but I don't know how to implement this things in CSS... I have fast tried..

**Comment by emviveros** [comment]
The point 2. is a little DOM issue.. Not really important. It's already very very good!

**Comment by Lucarda** [comment]
I think both things are fixed by shrinking larger images than the view-port.

I had updated the CSS. please test.
(you might need to clear the browser cache.)

**Comment by porres** [comment]
what's up with this?

**Comment by Lucarda** [comment]
Miller didn't like the **Font** and/or **Theme** switching because it contained javascrpt.

I'm Ok with the decision.

Things that got included (and already merged with #1349) are:

- reworks "Chapter 1"

  - more explicit explanation of the "doc" sub-folders.

  - warms of outdated FLOSS manuals.
  
- Changes in the CSS file (font, font-sizes, font-colors).

- Updated images.

- Resize automatically images to maintain layout in mobile

(I had deleted the previews from the links above to not pollute google searches on the Pd manual)

**Comment by Lucarda** [comment]
May be this can be closed. Feel free to re-open.

**Comment by porres** [comment]
I wonder if it's even worth praising and mentioning 'Floss Manuals' with that kind of emphasis... what's good about it as an actual 'manual'?

**Comment by porres** [comment]
this is closed but still appears as 'pinned'

**Comment by Lucarda** [comment]
unpinned
