### ISSUE TITLE
there's an undocumented 'range' method for [text search]

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#91]

**Comment by abreubacelar** [comment]
About this issue... actually there was an documented range method that was lost...

see https://github.com/pure-data/pure-data/commit/48f783158cc012ef563ca2abd802e3204106400b

when miller created the feature, he documented it, but probably some documentation pr after deleted it

**Comment by umlaeute** [comment]
the update that lost the `range` message was 01be2915c397df4e083ef5796c4ee07b1a0bedd2

**Comment by porres** [comment]
oops :/
