### ISSUE TITLE
document triggerize, intelligent patching and more editting goodies into the manual

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#92]
this should be in the manual but maybe have some pointers in the docs.

This is the list of things I'll work and add to the manual, you can also edit and send suggestions in PRs to this branch in my repo

- [x] Document 'cmd+e' shortcut

- [ ] Document 'tab' navigation 

- [ ] Document 'esc' to cancel selection 

- [ ] Document autopatching

- [ ] improve copy/paste/duplicate/cut section specially by documenting 'paste + replace'

- [ ] Document aligning objects stuff

- [ ] Document triggerize

- [ ] Document intelligent patching

**Comment by abreubacelar** [comment]
about this issue, i am planning to add an appendix like the one i am proposing in https://github.com/pure-data/pddp/issues/111 on manual...

So appendix A would be for properties dialogs, and appendix B could be for Intelligent Patching (and then we can add triggerize and autopatching together since they are in the same context)

and if you like this format, we could think about other appendix with references in the future, like shortcuts references, and then the html references for the objects could go in one of those... what do you think?

i think it makes sense to show the process of intelligent patching with gifs, but i'm not sure if it is fine to add them to the manual... @Lucarda ?

**Comment by Lucarda** [comment]
> i think it makes sense to show the process of intelligent patching with gifs, but i'm not sure if it is fine to add them to the manual... @Lucarda ?

Lets go step by step. I would like to say a couple of things about #111.  Eventually yes, if we are going to start documenting stuff we'll need (for now) more appendixes.

**Comment by porres** [comment]
@ben-wes can you help us? @Lucarda can you help ben? Let's do this now finally so we can include it in 0.55 coming up next month! You can send a PR to my documentation updates I guess.

**Comment by ben-wes** [comment]
i collected stuff to contribute to the interaction design of the plugdata project - this might be a good starting point for our documentation here:
https://github.com/plugdata-team/plugdata/discussions/1474

... i'll gladly rephrase stuff and restructure it! let me know what you think about the general structure i chose there and i'll try to update this content accordingly for Pd!

**Comment by Lucarda** [comment]
ok, this is my suggested method to get it into 0.55 manual.

- @ben-wes creates a folder with an `.md` file in https://github.com/pure-data/pddp

say: `https://github.com/pure-data/pddp/keyboard-interaction/keyboard.md`

- `keyboard.md` contains roughly https://github.com/plugdata-team/plugdata/discussions/1474#discussion-6356628 but without the check-boxes and without the **plugdata** annotations.

  - we all edit this file until we think we had covered all.
  
  - i think its fine to include the `vimeos` for "intelligent patching" as an online resource (just the links) (we are not going to add videos or such big gif animations to the Pd repo)
  
- I[*] create an `pure-data/doc/1.manual/x7.htm` from the `.md` file.

- I[*] update `pure-data/doc/1.manual/index.htm`.

- I[*] create a PR for `documentation` branch and we are done.


[*] if anyone feels comfortable manually inserting all the internal linking structure of the HTML code go ahead and do it.

-----------

I think "Pd Manual chapter 7: keyboard interaction" will do? what do you say?

**Comment by porres** [comment]
> "Pd Manual chapter 7: keyboard interaction" will do? what do you say?

it's not only keyboard, we also have mouse interactions.

I think this could be a part of x2.htm under 2.2. editing Pd patches

**Comment by Lucarda** [comment]
> I think this could be a part of x2.htm under 2.2. editing Pd patches

could be. but let's go by steps and have the `.md`.

**Comment by porres** [comment]
> let's go by steps and have the .md.

sure

**Comment by Lucarda** [comment]
@ben-wes  I recognize you as the author and i think it will be better if you do the HTML part and get the commit[*] into the manual. I'm offering myself to keep uncertainty and doubt out of the way. May be you have something in mind to get it done. Please let us know. If not, let's continue.

[*] I would like the we squash everything into a single commit into `documentation` branch so it can be easily disapproved and undone by @millerpuckette.

**Comment by porres** [comment]
@Lucarda, @ben-wes cannot really do the HTML part I guess. Neither can I. We need your help to put the content into the html manual properly. I can help, co author and revise

**Comment by porres** [comment]
> I would like the we squash everything into a single commit
+1

**Comment by Lucarda** [comment]
> @Lucarda, @ben-wes cannot really do the HTML part I guess. Neither can I. We need your help to put the content into the html manual properly. I can help, co author and revise

No trouble. I just needed to speak. lets continue...

**Comment by Lucarda** [comment]
I'm not sure if the new block fits in chapter 2 when we are just reading a broad explication. I would like this stuff somewhere else.

see [preview-chapter2-v1.zip](https://github.com/pure-data/pddp/files/14583594/preview-chapter2-v1.zip)

**Comment by ben-wes** [comment]
@porres @Lucarda thanks a lot for the discussion and preparations here and sorry for not joining earlier - i blame it on my time zone and other work! :)

i was originally even thinking of some kind of cheatsheet that would show all available shortcuts and interactions. for me, all options are fine and i also wouldn't mind to have this (quite relevant) information redundantly at two locations (although maintaining it is less fun then).

i don't mind editing html - but just to be sure: so are we dealing with static html here? this isn't generated? either way, i agree that collaborating on markdown is certainly the better option.

so i'd create a branch on my side with https://github.com/pure-data/pddp/keyboard-interaction/keyboard.md? or should we put this here in the main branch even though it's a temporary state?

**Comment by ben-wes** [comment]
current version is here:
https://github.com/ben-wes/pddp/blob/shortcuts/keyboard-interaction/shortcuts.md

but i'm open to any changes concerning content and workflow obviously!

**Comment by Lucarda** [comment]
> cmd vs. ctrl?

I think `cmd` is ok and understandable by anyone.

Can you make a PR to this repo that adds the file ?

**Comment by Lucarda** [comment]
@ben-wes what do you say chapter2 or chapter7?

**Comment by ben-wes** [comment]
> @ben-wes what do you say chapter2 or chapter7?

imho, it gets quite buried in chapter2. how about adding chapter7 and adding a link in chapter2?

**Comment by Lucarda** [comment]
> mho, it gets quite buried in chapter2. how about adding chapter7 and adding a link in chapter2?

Yes. I agree and like it most. but lets wait for @porres. (until we convince him)

**Comment by Lucarda** [comment]
In the mean time we can think of something else we can add to chapter 7

**Comment by porres** [comment]
why would it get buried in chapter 2? This is a central software operational information, how to patch, how to make connections, how to disconnect, shortcuts for copy/past, get in and out of edit mode, it's all in there already. I honestly cannot see how this is a separate chapter...

**Comment by porres** [comment]
btw, it's been on my list forever to make a deep and big revision and overhaul of the manual. Add lots of more stuff and information.

One thing I'd like to do is going over ALL MENUS in Pd! Posting some screenshots and detail all options and menu entries. We can start with the 'Edit' and "Put' Menus, which relate to this chapter and edditing patches, and some of the shortcuts are there, like triggerize

**Comment by ben-wes** [comment]
i can't contradict when it comes to chapter2 being the right place to mention that stuff. totally agreed. but since new users will probably need to check these methods repeatedly before really adapting them and saving them in their muscle memory, something a bit more "cheatsheet"-like would be nice, where they don't need to scroll a lot to find these informations. i just assume that this page will be opened a bit more than a general introduction.

but in the end, it's good to have it somewhere - no matter where. so i'm fine with any option!

**Comment by ben-wes** [comment]
> One thing I'd like to do is going over ALL MENUS in Pd! Posting some screenshots and detail all options and menu entries. We can start with the 'Edit' and "Put' Menus, which relate to this chapter and edditing patches, and some of the shortcuts are there, like triggerize

sounds great! btw, i would also be willing to create animated gifs for the intelligent patching stuff. might be slightly more accessible than the textual explanations ...

**Comment by Lucarda** [comment]
> btw, it's been on my list forever to make a deep and big revision and overhaul of the manual ...

Right. Wait. You know https://github.com/pure-data/pure-data/pull/1822 got stuck. this is what you are going to need for an overhaul. For now lets just do something possible.

**Comment by porres** [comment]
> i can't contradict when it comes to chapter2 being the right place to mention that stuff. totally agreed. but since new users will probably need to check these methods repeatedly before really adapting them and saving them in their muscle memory, something a bit more "cheatsheet"-like would be nice, where they don't need to scroll a lot to find these informations. i just assume that this page will be opened a bit more than a general introduction.
> 
> but in the end, it's good to have it somewhere - no matter where. so i'm fine with any option!

maybe my view is not clear, and out views differ. I jus t had a look at that document and surely enough it looks like a cheatsheet or something, and an appendix of some sort. But this is not what I had in mind. I'm looking at a very detailed step by step description with screenshots and everything...

**Comment by porres** [comment]
> sounds great! btw, i would also be willing to create animated gifs for the intelligent patching stuff. might be slightly more accessible than the textual explanations ...

ok, now we're talking... yeah, just not sure if we have animated gifs already. Would not be good for a printed version though

**Comment by porres** [comment]
I thought of screesnhots that give you the idea, and yeah, I'm thinking of putting into a manual like step by step thing all that those vimeo videos have and more...

if you know me well, I'm kinda crazy and I don't fool around, I go for an obsessive compulsive option always

**Comment by porres** [comment]
this md is a nice list document to start with...

**Comment by Lucarda** [comment]
>  I'm looking at a very detailed step by step description with screenshots and everything...

:-1:

**Comment by porres** [comment]
what's the problem @Lucarda ? :)

**Comment by ben-wes** [comment]
> if you know me well, I'm kinda crazy and I don't fool around, I go for an obsessive compulsive option always

haha, ok - and this can certainly be a good thing. :) i think that in this situation though, we should structure it in a way that people can go from rough to detailed (or vice versa). i don't see cheatsheet and comprehensive explanation as exclusive options. why not have both? 

the obsessive, compulsive option can certainly become a bit overwhelming for the beginning. i'm happy with that in general ... but brief information is more accessible imho.

**Comment by Lucarda** [comment]
Let's go by steps.

- we create chapter 7 with the nice and useful info we can get from the `.md`.
  - (optionally @ben-wes finds time to do his animated gifs and we see if they are to be included)

the other stuff waits until we have this done.

**Comment by Lucarda** [comment]
for technical reasons we continue editing the `.md` file with just headings, `code`, lists, links and we can ad images. thats all we support in the current CSS.

**Comment by Lucarda** [comment]
> what's the problem @Lucarda ? :)

@porres and @ben-wes feel free to include the "obsessive compulsive option" to chapter 7.

this is a lot of work you can do.

**Comment by Lucarda** [comment]
@ben-wes you can add the images in the same folder as the `.md`. When you are done create a PR just like the other one.

**Comment by ben-wes** [comment]
> this is a lot of work you can do.

certainly so! :) i'm not sure though if i can contribute a lot there. maybe this should be an aim for beyond 0.55? anyway, i'd certainly be glad to see a brief version included in 0.55 that can be referred to for new users!

so for now, i'd try to proceed with the current md in a way that it feels well structured and blends in with the existing docs. are you planning to edit there as well, @porres and @Lucarda ? or should we discuss changes here?

**Comment by ben-wes** [comment]
> @ben-wes you can add the images in the same folder as the `.md`. When you are done create a PR just like the other one.

alright. i'd do that last though. after all, we could also link to the existing videos for a start (if there are no objections).

**Comment by Lucarda** [comment]
> alright. i'd do that last though. after all, we could also link to the existing videos for a start (if there are no objections).

links are preferred. let's try to avoid animated gifs.  @millerpuckette has expressed his concerns in using the fewer computational load possible for the browser when going through the manual. No javascript, no nothing. (i had only violated this in the deken.gif)

https://github.com/pure-data/pddp/issues/111#issuecomment-1329418347

**Comment by porres** [comment]
I am not convinced there should be a chapter 7 for this. I said that, as it is, this looks like an awesome ppendix or something. A simple document... and, as so, I could see it as something extra. Let me be clear though, I don't like this idea and even something short like this could be easily integrated into chapter 2, along with the other things that are already there.

We can make something quick, aiming at a new pd update in a month, and work beyond it.

For reference, I made a complete overhaul of chapter 4, which was basically something else on 'how to write externals', and it was short. I made it a section about deken and installing externals, and it wasn't done overnight, as a single commit, for a single update.

This md document is a good starting point list of things we should include in the manual, let me go over it and also contribute to it. Yes, I want to contribute to it... 

I think we can work on it in a branch though, and not polute 'main' with it.

**Comment by Lucarda** [comment]
@porres you have super-cow powers to create a branch. (let us know when you had created one)

@ben-wes if @porres has created a branch before your PR try to target to that `branch`.

**Comment by Lucarda** [comment]
@ben-wes and @porres i had created `wip-0.55` branch.

**Comment by porres** [comment]
Ok, looking at the document. It's mostly a list of what is already listed as shortcuts in the Edit and Put Menus... 

some remarks

## mode management

not sure what 'mode management' is supposed to mean here...

The command thing enabling run mode while in edit mode is something I already documented in my documentation branch... I didn't mention listed shortucts, but we can start.... 'ctrl/cmd + e' being the most obvious one...

- The tab thing seems weird, I dont get... tab really navigates through selected objects... something to properly document

- `esc` cancels selection (unselects everything). Ok, but so what? Why here?

- There's no need to give object names for GUIs, there are shortcuts for them and their names are given in the help files

#### connect new object to selected object

- I think you are describing 'autopatch', which is something you can disable via a flag. We should cover this in the manual better

Anyway, the list as it is not very descriptive, as with triggerize. I don't think this makes sense, unless you already know what triggerize is, and then this is just a quite simple description of what is already listed in the Edit menu as a shortcut... we should better explain in the manual with pictures and stuff 

- most of the copy/paste section is already described in the manual, should just be improved...

- aligning objects, ok, should also be added

- I dont know wht a `cmd + r` shortcut is here... it is in the 'Window' Menu

- The rest is just a good start to start documenting inteligent patching.

I guess I'll start a manual update branch in the pure data branch to start adding things there and I can just make a single commit to the documentation branch

**Comment by porres** [comment]
doing it here https://github.com/pure-data/pure-data/compare/master...porres:pure-data:manual-intelligent-patching

from here https://github.com/pure-data/pure-data/commit/7491004744c9653c46dacb62c3b5b5d92e4ea90e

**Comment by porres** [comment]
This is the list of things I'll work and add to the manual, you can also edit and send suggestions in PRs to this branch in my repo

- [ ] Document 'cmd+e' shortcut

- [ ] Document 'tab' navigation 

- [ ] Document 'esc' to cancel selection 

- [ ] Document autopatching

- [ ] improve copy/paste/duplicate/cut section specially by documenting 'paste + replace'

- [ ] Document aligning objects stuff

- [ ] Document triggerize

- [ ] Document intelligent patching

**Comment by porres** [comment]
damn, I'll just reboot this

**Comment by porres** [comment]
ok, moving to https://github.com/pure-data/pddp/issues/186

**Comment by ben-wes** [comment]
> The command thing enabling run mode while in edit mode is something I already documented in my documentation branch... I didn't mention listed shortucts, but we can start.... 'ctrl/cmd + e' being the most obvious one...

just to go sure that there's not misunderstanding here, @porres: i created this list mainly for the plugdata side since i had the feeling that i can't really patch quickly there. so this was initiated as my "personal patterns". i then pointed you to this since i thought that there might be stuff included that's relevant for vanilla users, too. i explicitly did not check the whole documentation first since my idea was a cheatsheet (like i wrote). so i'm sorry if this is not perfect and redundant for the documentation context yet - but that was also not what i wrote it for originally. i was summoned here by you. :)
 
> * The tab thing seems weird, I dont get... tab really navigates through selected objects... something to properly document

if you're patching mainly with keyboard, it's a good way to get out of the keyboard text editing for me (and confirm the object creation therefore) since i can reach it easier with my fingers than `esc` ... but yeah, it is actually just cycling through objects - which i also mention.

> * `esc` cancels selection (unselects everything). Ok, but so what? Why here?

i use it quite often in the context of moving objects with the mouse since otherwise, i tend to get to the text editing. but yeah - it might not be relevant. for a cheatsheet it would be relevant imho though. 

> * There's no need to give object names for GUIs, there are shortcuts for them and their names are given in the help files

for me there is. i know there are shortcuts for these and they're visible in the menu. but i can't easily remember `cmd + shift + j`, `cmd + shift + d`, `cmd + shift + i`. i can very easily remember the names of these objects though and create them simply by `ctrl + 1` and their (short) name. again, maybe not relevant here - but i think, i might not be the only one and it's nice if users can at least get this information somewhere when learning about patching.

> * I dont know wht a `cmd + r` shortcut is here... it is in the 'Window' Menu

this doesn't do anything on the plugdata side, and it would need to be listed on a cheatsheet - hence the mention here. :)

> I guess I'll start a manual update branch in the pure data branch to start adding things there and I can just make a single commit to the documentation branch

sounds good!

**Comment by ben-wes** [comment]
> repeatedly pressing `cmd + k` when upper object has 1 outlet and lower one has more: connects multiple connections to all inlets of lower object (NOT TRUE for me @ben-wes )

true for signal rate connections. but i wasn't specific there, sorry. i used this a lot for squaring values via two connections to `[*~]`

**Comment by ben-wes** [comment]
> avoiding there one of the most common patching mistakes [...]

adding to this: a list of common mistakes in some faq way somewhere might be nice, too. :)
